test infinite loop

diff --git a/src/AOloopControl/scripts/aolconf b/src/AOloopControl/scripts/aolconf
--- a/src/AOloopControl/scripts/aolconf
+++ b/src/AOloopControl/scripts/aolconf
@@ -600,6 +600,11 @@ if ! [ -x "$(command -v dialog)" ]; then
   exit 1
 fi
 
+if ! [ -x "$(command -v tmux)" ]; then
+  echo 'Error: tmux is not installed.' >&2
+  exit 1
+fi
+
 
 while true; do
 echo "LOOP START"
