error checking added on bash scripts

diff --git a/AOloopControl/examples/scexao-vispyr-bin2-conf/scripts/aorun-setmode-hardw b/AOloopControl/examples/scexao-vispyr-bin2-conf/scripts/aorun-setmode-hardw
--- a/AOloopControl/examples/scexao-vispyr-bin2-conf/scripts/aorun-setmode-hardw
+++ b/AOloopControl/examples/scexao-vispyr-bin2-conf/scripts/aorun-setmode-hardw
@@ -1,7 +1,7 @@
 #!/usr/bin/env bash
 
 # This script uses milk-argparse
-# See template milk-scriptexample in module milk_module_example for template and instructions
+# See milk-scriptexample for template and instructions
 
 # script 1-line description
 MSdescr="set hardware configuration"
@@ -12,13 +12,11 @@ MSextdescr="Hardware mode
 source milk-script-std-config
 source cacao-check-cacaovars
 
+RequiredCommands=( cacao-setDMnolink )
+
 source milk-argparse
 
 
-
-
-
-errexit=0
 
 # Checking required FPS
 FPScheckOK="OK"
@@ -26,85 +24,69 @@ checkFPSON CACAO_FPSPROC_ACQUWFS ${CACAO_FPSPROC_ACQUWFS}
 checkFPSON CACAO_FPSPROC_MVMGPU_WFS2CMODEVAL ${CACAO_FPSPROC_MVMGPU_WFS2CMODEVAL}
 checkFPSON CACAO_FPSPROC_MODALFILTERING ${CACAO_FPSPROC_MODALFILTERING}
 checkFPSON CACAO_FPSPROC_MVMGPU_CMODEVAL2DM ${CACAO_FPSPROC_MVMGPU_CMODEVAL2DM}
-
-
+checkFPSON CACAO_FPSPROC_MEASURELINRESP ${CACAO_FPSPROC_MEASURELINRESP}
 
 if [ ${FPScheckOK} == "FAIL" ]; then
-echo "[$(tput setaf 1)$(tput bold) FAILED $(tput sgr0)] FPS check failed"
-errexit=1
+	echo "[$(tput setaf 1)$(tput bold) FAILED $(tput sgr0)] FPS check failed"
+	cacaomsglog "ERROR FPScheck"
+	exit 1
 fi
 
 
-if [ $errexit = 1 ]; then
-exit
-fi
 
-
-sendFPScmd "setval acquWFS-0.WFSnormfloor 0.1"
-
-
-sendFPScmd "setval DMch2disp-${CACAO_DMINDEX}.AveMode 1"
-sendFPScmd "setval DMch2disp-${CACAO_DMINDEX}.option.voltmode ON"
-sendFPScmd "setval DMch2disp-${CACAO_DMINDEX}.option.volttype 2"
-sendFPScmd "setval DMch2disp-${CACAO_DMINDEX}.option.stroke100 1.0"
-sendFPScmd "setval DMch2disp-${CACAO_DMINDEX}.option.voltname dmvolt"
-sendFPScmd "setval DMch2disp-${CACAO_DMINDEX}.option.DClevel 0.7"
-sendFPScmd "setval DMch2disp-${CACAO_DMINDEX}.option.maxvolt 150.0"
-sendFPScmd "confwupdate DMch2disp-${CACAO_DMINDEX}"
 
 
 sendFPScmd "setval measlinresp-${CACAO_LOOPNUMBER}.ampl 0.03"
 sendFPScmd "setval measlinresp-${CACAO_LOOPNUMBER}.timing.NBave 5"
 sendFPScmd "setval measlinresp-${CACAO_LOOPNUMBER}.timing.NBexcl 1"
 sendFPScmd "setval measlinresp-${CACAO_LOOPNUMBER}.timing.NBinnerCycle 10"
-sendFPScmd "setval measlinresp-${CACAO_LOOPNUMBER}.procinfo.loopcntMax 20"
+sendFPScmd "setval measlinresp-${CACAO_LOOPNUMBER}.procinfo.loopcntMax 80"
 
 
 sendFPScmd "setval wfs2cmodeval-${CACAO_LOOPNUMBER}.GPUindex 1"
 sendFPScmd "confwupdate wfs2cmodeval-${CACAO_LOOPNUMBER}"
 
-sendFPScmd "setval mvalC2dm-${CACAO_LOOPNUMBER}.GPUindex 3"
+sendFPScmd "setval mvalC2dm-${CACAO_LOOPNUMBER}.GPUindex 1"
 sendFPScmd "confwupdate mvalC2dm-${CACAO_LOOPNUMBER}"
 
 
-# stream linking
+
 
 # WFS
 echo "Linking WFS"
 
 ln -sf ${MILK_SHM_DIR}/${CACAO_WFSSTREAM}.im.shm ${MILK_SHM_DIR}/aol${CACAO_LOOPNUMBER}_wfsim.im.shm
 
-
 sendFPScmd "setval acquWFS-${CACAO_LOOPNUMBER}.insname aol${CACAO_LOOPNUMBER}_wfsim"
 sendFPScmd "setval acquWFS-${CACAO_LOOPNUMBER}.WFSnormfloor 0.1"
 sendFPScmd "confwupdate acquWFS-${CACAO_LOOPNUMBER}"
 
 # DM
+
+echo "Switching to hardware DM"
+DMINDEX="${CACAO_DMINDEX}"
+echo "${DMINDEX}" > DMINDEX
+
 echo "Linking DM"
+cacao-setDMnolink
 
-ln -sf ${MILK_SHM_DIR}/dm${CACAO_DMINDEX}disp03.im.shm ${MILK_SHM_DIR}/aol${CACAO_LOOPNUMBER}_dmC.im.shm
+sendFPScmd "setval DMch2disp-${DMINDEX}.AveMode 1"
+sendFPScmd "setval DMch2disp-${DMINDEX}.option.voltmode ON"
+sendFPScmd "setval DMch2disp-${DMINDEX}.option.volttype 2"
+sendFPScmd "setval DMch2disp-${DMINDEX}.option.stroke100 1.0"
+sendFPScmd "setval DMch2disp-${DMINDEX}.option.voltname dmvolt"
+sendFPScmd "setval DMch2disp-${DMINDEX}.option.DClevel 0.7"
+sendFPScmd "setval DMch2disp-${DMINDEX}.option.maxvolt 150.0"
+sendFPScmd "confwupdate DMch2disp-${DMINDEX}"
 
-ln -sf ${MILK_SHM_DIR}/dm${CACAO_DMINDEX}disp00.im.shm ${MILK_SHM_DIR}/aol${CACAO_LOOPNUMBER}_dmO.im.shm
-
-ln -sf ${MILK_SHM_DIR}/dm${CACAO_DMINDEX}disp04.im.shm ${MILK_SHM_DIR}/aol${CACAO_LOOPNUMBER}_dmZP0.im.shm
-ln -sf ${MILK_SHM_DIR}/dm${CACAO_DMINDEX}disp05.im.shm ${MILK_SHM_DIR}/aol${CACAO_LOOPNUMBER}_dmZP1.im.shm
-ln -sf ${MILK_SHM_DIR}/dm${CACAO_DMINDEX}disp06.im.shm ${MILK_SHM_DIR}/aol${CACAO_LOOPNUMBER}_dmZP2.im.shm
-ln -sf ${MILK_SHM_DIR}/dm${CACAO_DMINDEX}disp07.im.shm ${MILK_SHM_DIR}/aol${CACAO_LOOPNUMBER}_dmZP3.im.shm
-ln -sf ${MILK_SHM_DIR}/dm${CACAO_DMINDEX}disp08.im.shm ${MILK_SHM_DIR}/aol${CACAO_LOOPNUMBER}_dmZP4.im.shm
-ln -sf ${MILK_SHM_DIR}/dm${CACAO_DMINDEX}disp09.im.shm ${MILK_SHM_DIR}/aol${CACAO_LOOPNUMBER}_dmZP5.im.shm
-ln -sf ${MILK_SHM_DIR}/dm${CACAO_DMINDEX}disp10.im.shm ${MILK_SHM_DIR}/aol${CACAO_LOOPNUMBER}_dmZP6.im.shm
-ln -sf ${MILK_SHM_DIR}/dm${CACAO_DMINDEX}disp11.im.shm ${MILK_SHM_DIR}/aol${CACAO_LOOPNUMBER}_dmZP7.im.shm
-
-ln -sf ${MILK_SHM_DIR}/dm${CACAO_DMINDEX}disp02.im.shm ${MILK_SHM_DIR}/aol${CACAO_LOOPNUMBER}_dmRM.im.shm
-
-ln -sf ${MILK_SHM_DIR}/dm${CACAO_DMINDEX}disp10.im.shm ${MILK_SHM_DIR}/aol${CACAO_LOOPNUMBER}_dmturb.im.shm
-
-ln -sf ${MILK_SHM_DIR}/dm${CACAO_DMINDEX}disp.im.shm ${MILK_SHM_DIR}/aol${CACAO_LOOPNUMBER}_dmdisp.im.shm
 
 
 # update system cacaoloop record
 #
 CACAOLOOPRECORD="${MILK_SHM_DIR}/cacaoloop-${CACAO_LOOPNUMBER}"
 mkdir -p ${CACAOLOOPRECORD}
-echo "${CACAO_DMINDEX}" > ${CACAOLOOPRECORD}/dmindex
+echo "${DMINDEX}" > ${CACAOLOOPRECORD}/dmindex
 echo "${CACAO_WFSSTREAM}" > ${CACAOLOOPRECORD}/wfsim
+
+
+cacaomsglog "END"
diff --git a/AOloopControl/examples/scexao-vispyr-bin2-conf/scripts/aorun-setmode-sim b/AOloopControl/examples/scexao-vispyr-bin2-conf/scripts/aorun-setmode-sim
--- a/AOloopControl/examples/scexao-vispyr-bin2-conf/scripts/aorun-setmode-sim
+++ b/AOloopControl/examples/scexao-vispyr-bin2-conf/scripts/aorun-setmode-sim
@@ -12,77 +12,79 @@ MSextdescr="Simulation mode
 source milk-script-std-config
 source cacao-check-cacaovars
 
+RequiredCommands=( cacao-setDMnolink )
+
+
 source milk-argparse
 
 
 
 
 
-errexit=0
 
 # Checking required FPS
 FPScheckOK="OK"
 checkFPSON CACAO_FPSPROC_ACQUWFS ${CACAO_FPSPROC_ACQUWFS}
-#checkFPSON CACAO_FPSPROC_ACQLINZRM ${CACAO_FPSPROC_ACQLINZRM}
-#checkFPSON CACAO_FPSPROC_ACQLINLORM ${CACAO_FPSPROC_ACQLINLORM}
+checkFPSON CACAO_FPSPROC_WFSCAMSIM ${CACAO_FPSPROC_WFSCAMSIM}
+checkFPSON CACAO_FPSPROC_MVMGPU_WFS2CMODEVAL ${CACAO_FPSPROC_MVMGPU_WFS2CMODEVAL}
+checkFPSON CACAO_FPSPROC_MVMGPU_CMODEVAL2DM ${CACAO_FPSPROC_MVMGPU_CMODEVAL2DM}
+checkFPSON CACAO_FPSPROC_MEASURELINRESP ${CACAO_FPSPROC_MEASURELINRESP}
 
 if [ ${FPScheckOK} == "FAIL" ]; then
-echo "[$(tput setaf 1)$(tput bold) FAILED $(tput sgr0)] FPS check failed"
-errexit=1
-fi
-
-
-if [ $errexit = 1 ]; then
-exit
+	echo "[$(tput setaf 1)$(tput bold) FAILED $(tput sgr0)] FPS check failed"
+	cacaomsglog "ERROR FPScheck"
+	exit 1
 fi
 
 
 
+sendFPScmd "setval measlinresp-${CACAO_LOOPNUMBER}.ampl 0.03"
+sendFPScmd "setval measlinresp-${CACAO_LOOPNUMBER}.timing.NBave 5"
+sendFPScmd "setval measlinresp-${CACAO_LOOPNUMBER}.timing.NBexcl 1"
+sendFPScmd "setval measlinresp-${CACAO_LOOPNUMBER}.timing.NBinnerCycle 10"
+sendFPScmd "setval measlinresp-${CACAO_LOOPNUMBER}.procinfo.loopcntMax 20"
 
-sendFPScmd "setval wfscamsim-${CACAO_LOOPNUMBER}.compphnoise OFF"
-sendFPScmd "confwupdate wfscamsim-${CACAO_LOOPNUMBER}"
 
 
+sendFPScmd "setval wfs2cmodeval-${CACAO_LOOPNUMBER}.GPUindex 0"
+sendFPScmd "confwupdate wfs2cmodeval-${CACAO_LOOPNUMBER}"
+
+sendFPScmd "setval mvalC2dm-${CACAO_LOOPNUMBER}.GPUindex 0"
+sendFPScmd "confwupdate mvalC2dm-${CACAO_LOOPNUMBER}"
 
 
-
-# stream linking
 
 # WFS
 echo "Linking WFS"
 
 ln -sf ${MILK_SHM_DIR}/${CACAO_WFSSTREAMSIM}.im.shm ${MILK_SHM_DIR}/aol${CACAO_LOOPNUMBER}_wfsim.im.shm
 
+sendFPScmd "setval wfscamsim-${CACAO_LOOPNUMBER}.compphnoise OFF"
+sendFPScmd "confwupdate wfscamsim-${CACAO_LOOPNUMBER}"
 sendFPScmd "setval acquWFS-${CACAO_LOOPNUMBER}.insname aol${CACAO_LOOPNUMBER}_wfsim"
 sendFPScmd "setval acquWFS-${CACAO_LOOPNUMBER}.WFSnormfloor 0.01"
 
 
+
 # DM
+echo "Switching to simulation DM"
+DMINDEX="${CACAO_DMSIMINDEX}"
+echo "${DMINDEX}" > DMINDEX
+
 echo "Linking DM"
+cacao-setDMnolink
 
-ln -sf ${MILK_SHM_DIR}/dm${CACAO_DMSIMINDEX}disp03.im.shm ${MILK_SHM_DIR}/aol${CACAO_LOOPNUMBER}_dmC.im.shm
 
-ln -sf ${MILK_SHM_DIR}/dm${CACAO_DMSIMINDEX}disp00.im.shm ${MILK_SHM_DIR}/aol${CACAO_LOOPNUMBER}_dmO.im.shm
 
-ln -sf ${MILK_SHM_DIR}/dm${CACAO_DMSIMINDEX}disp04.im.shm ${MILK_SHM_DIR}/aol${CACAO_LOOPNUMBER}_dmZP0.im.shm
-ln -sf ${MILK_SHM_DIR}/dm${CACAO_DMSIMINDEX}disp05.im.shm ${MILK_SHM_DIR}/aol${CACAO_LOOPNUMBER}_dmZP1.im.shm
-ln -sf ${MILK_SHM_DIR}/dm${CACAO_DMSIMINDEX}disp06.im.shm ${MILK_SHM_DIR}/aol${CACAO_LOOPNUMBER}_dmZP2.im.shm
-ln -sf ${MILK_SHM_DIR}/dm${CACAO_DMSIMINDEX}disp07.im.shm ${MILK_SHM_DIR}/aol${CACAO_LOOPNUMBER}_dmZP3.im.shm
-ln -sf ${MILK_SHM_DIR}/dm${CACAO_DMSIMINDEX}disp08.im.shm ${MILK_SHM_DIR}/aol${CACAO_LOOPNUMBER}_dmZP4.im.shm
-ln -sf ${MILK_SHM_DIR}/dm${CACAO_DMSIMINDEX}disp09.im.shm ${MILK_SHM_DIR}/aol${CACAO_LOOPNUMBER}_dmZP5.im.shm
-ln -sf ${MILK_SHM_DIR}/dm${CACAO_DMSIMINDEX}disp10.im.shm ${MILK_SHM_DIR}/aol${CACAO_LOOPNUMBER}_dmZP6.im.shm
-ln -sf ${MILK_SHM_DIR}/dm${CACAO_DMSIMINDEX}disp11.im.shm ${MILK_SHM_DIR}/aol${CACAO_LOOPNUMBER}_dmZP7.im.shm
 
-ln -sf ${MILK_SHM_DIR}/dm${CACAO_DMSIMINDEX}disp02.im.shm ${MILK_SHM_DIR}/aol${CACAO_LOOPNUMBER}_dmRM.im.shm
-
-ln -sf ${MILK_SHM_DIR}/dm${CACAO_DMSIMINDEX}disp10.im.shm ${MILK_SHM_DIR}/aol${CACAO_LOOPNUMBER}_dmturb.im.shm
-
-ln -sf ${MILK_SHM_DIR}/dm${CACAO_DMSIMINDEX}disp.im.shm ${MILK_SHM_DIR}/aol${CACAO_LOOPNUMBER}_dmdisp.im.shm
 
 
 # update system cacaoloop record
 #
 CACAOLOOPRECORD="${MILK_SHM_DIR}/cacaoloop-${CACAO_LOOPNUMBER}"
 mkdir -p ${CACAOLOOPRECORD}
-echo "${CACAO_DMSIMINDEX}" > ${CACAOLOOPRECORD}/dmindex
+echo "${DMINDEX}" > ${CACAOLOOPRECORD}/dmindex
 echo "${CACAO_WFSSTREAMSIM}" > ${CACAOLOOPRECORD}/wfsim
+
+
+cacaomsglog "END"
diff --git a/AOloopControl/scripts/aorun/cacao-aorun-000-dm b/AOloopControl/scripts/aorun/cacao-aorun-000-dm
--- a/AOloopControl/scripts/aorun/cacao-aorun-000-dm
+++ b/AOloopControl/scripts/aorun/cacao-aorun-000-dm
@@ -18,7 +18,6 @@ DM channels (by default 12) are dm${DMindex}disp<channel>
 
 
 source milk-script-std-config
-
 source cacao-check-cacaovars
 
 MSarg+=( "action:string:action (start/stop/check)" )
@@ -35,7 +34,7 @@ ACTIONOK=0
 
 
 if [ ${ACTION} == "check" ]; then
-ACTIONOK=1
+	ACTIONOK=1
 fi
 
 # Checking FPS
@@ -44,63 +43,64 @@ checkFPSON CACAO_FPSPROC_DMCH2DISP ${CACAO_FPSPROC_DMCH2DISP}
 echo "FPScheckOK = ${FPScheckOK}"
 
 if [ ${FPScheckOK} == "FAIL" ]; then
-echo "[$(tput setaf 1)$(tput bold) FAILED $(tput sgr0)] FPS check failed"
-exit
+	echo "[$(tput setaf 1)$(tput bold) FAILED $(tput sgr0)] FPS check failed"
+	exit 1
 fi
 
 set +e
 DMrunning=0
 pOK=$(ps -alx| grep DMch2disp-${CACAO_DMINDEX} | grep RUNSTART | wc -l)
 if [ $pOK -gt 0 ]; then
-echo "Process DMch2disp-${CACAO_DMINDEX} is already running"
-DMrunning=1
+	cacaomsglog "Process DMch2disp-${CACAO_DMINDEX} is already running"
+	DMrunning=1
 else
-echo "Process DMch2disp-${CACAO_DMINDEX} not currently running"
-DMrunning=0
+	cacaomsglog "Process DMch2disp-${CACAO_DMINDEX} not currently running"
+	DMrunning=0
 fi
 
 
 if [ ${ACTION} == "start" ]; then
-ACTIONOK=1
-cacaomsglog "START"
+	ACTIONOK=1
+	cacaomsglog "START"
 
-# ======================================================================
-# Starting DM combination process
-# ======================================================================
-if [ ${DMrunning} == "0" ]; then
-#sendFPScmd "setval DMch2disp-${CACAO_DMINDEX}.option.voltmode OFF"
-#sendFPScmd "setval DMch2disp-${CACAO_DMINDEX}.option.DClevel 0.0"
-#taskset_DMch2disp="3"
-#sendFPScmd "setval DMch2disp-${CACAO_DMINDEX}.procinfo.taskset ${taskset_DMch2disp}"
-sendFPScmd "confwupdate DMch2disp-${CACAO_DMINDEX}"
-sendFPScmd "runstart DMch2disp-${CACAO_DMINDEX}"
+	# ======================================================================
+	# Starting DM combination process
+	# ======================================================================
+	if [ ${DMrunning} == "0" ]; then
+		#sendFPScmd "setval DMch2disp-${CACAO_DMINDEX}.option.voltmode OFF"
+		#sendFPScmd "setval DMch2disp-${CACAO_DMINDEX}.option.DClevel 0.0"
+		#taskset_DMch2disp="3"
+		#sendFPScmd "setval DMch2disp-${CACAO_DMINDEX}.procinfo.taskset ${taskset_DMch2disp}"
+		sendFPScmd "confwupdate DMch2disp-${CACAO_DMINDEX}"
+		sendFPScmd "runstart DMch2disp-${CACAO_DMINDEX}"
 
-# WAIT for dm${CACAO_DMINDEX}disp to appear
-filename="${MILK_SHM_DIR}/dm${CACAO_DMINDEX}disp.im.shm"
-echo "Waiting for file ${filename} ..."
-until [ -f "$filename" ]
-do
-     sleep 0.1
-done
-milk-shmim-zero aol${CACAO_LOOPNUMBER}_dmC
-else
-cacaomsglog "DM already running -> nothing to do"
-fi
+		# WAIT for dm${CACAO_DMINDEX}disp to appear
+		filename="${MILK_SHM_DIR}/dm${CACAO_DMINDEX}disp.im.shm"
+		echo "Waiting for file ${filename} ..."
+		until [ -f "$filename" ]
+		do
+			sleep 0.1
+		done
+		milk-shmim-zero aol${CACAO_LOOPNUMBER}_dmC
+	else
+		cacaomsglog "DM already running -> nothing to do"
+	fi
 fi
 
 
 if [ ${ACTION} == "stop" ]; then
-ACTIONOK=1
-cacaomsglog "STOP"
-sendFPScmd "runstop DMch2disp-${CACAO_DMINDEX}"
+	ACTIONOK=1
+	cacaomsglog "STOP"
+	sendFPScmd "runstop DMch2disp-${CACAO_DMINDEX}"
 fi
 
 
 
 
 if [ ${ACTIONOK} == 0 ]; then
-echo "[$(tput setaf 1)$(tput bold) FAILED $(tput sgr0)] ACTION $ACTION undefined"
-cacaomsglog "ERROR action undefined"
+	echo "[$(tput setaf 1)$(tput bold) FAILED $(tput sgr0)] ACTION $ACTION undefined"
+	cacaomsglog "ERROR action undefined"
+	exit 1
 fi
 
 
diff --git a/AOloopControl/scripts/aorun/cacao-aorun-002-simwfs b/AOloopControl/scripts/aorun/cacao-aorun-002-simwfs
--- a/AOloopControl/scripts/aorun/cacao-aorun-002-simwfs
+++ b/AOloopControl/scripts/aorun/cacao-aorun-002-simwfs
@@ -30,7 +30,7 @@ ACTIONOK=0
 
 
 if [ ${ACTION} == "check" ]; then
-ACTIONOK=1
+	ACTIONOK=1
 fi
 
 # Checking FPS
@@ -40,108 +40,105 @@ checkFPSON CACAO_FPSPROC_DMSIMDELAY ${CACAO_FPSPROC_DMSIMDELAY}
 checkFPSON CACAO_FPSPROC_SIMMVMGPU ${CACAO_FPSPROC_SIMMVMGPU}
 
 if [ "$CACAO_WFSSTREAM_PROCESSED" = "ON" ]; then
-echo "Processed WFS stream -> no scaling"
+	echo "Processed WFS stream -> no scaling"
 else
-checkFPSON CACAO_FPSPROC_WFSCAMSIM ${CACAO_FPSPROC_WFSCAMSIM}
+	checkFPSON CACAO_FPSPROC_WFSCAMSIM ${CACAO_FPSPROC_WFSCAMSIM}
 fi
 
 echo "FPScheckOK = ${FPScheckOK}"
 
 if [ ${FPScheckOK} == "FAIL" ]; then
-echo "[$(tput setaf 1)$(tput bold) FAILED $(tput sgr0)] FPS check failed"
-exit
+	echo "[$(tput setaf 1)$(tput bold) FAILED $(tput sgr0)] FPS check failed"
+	exit 1
 fi
 
 
 
 
 if [ ${ACTION} == "start" ]; then
-ACTIONOK=1
-cacaomsglog "START"
-# ======================================================================
-# Starting DM hardware delay simulator
-# ======================================================================
+	ACTIONOK=1
+	cacaomsglog "START"
+	# ======================================================================
+	# Starting DM hardware delay simulator
+	# ======================================================================
 
-sendFPScmd "confwupdate DMstreamDelay-${CACAO_DMSIMINDEX}"
-sendFPScmd "runstart DMstreamDelay-${CACAO_DMSIMINDEX}"
-
-
-# ======================================================================
-# Starting MVM simulator
-# ======================================================================
-#sendFPScmd "setval simmvmgpu-${CACAO_LOOPNUMBER}.procinfo.triggerdelay ${TRIGDELAY}"
-sendFPScmd "confwupdate simmvmgpu-${CACAO_LOOPNUMBER}"
-sendFPScmd "runstart simmvmgpu-${CACAO_LOOPNUMBER}"
+	sendFPScmd "confwupdate DMstreamDelay-${CACAO_DMSIMINDEX}"
+	sendFPScmd "runstart DMstreamDelay-${CACAO_DMSIMINDEX}"
 
 
-# WAIT for aolX_linsimWFS to appear
-filename="${MILK_SHM_DIR}/aol${CACAO_LOOPNUMBER}_linsimWFS.im.shm"
-echo "Waiting for file ${filename} ..."
-until [ -f "$filename" ]
-do
-     sleep 0.1
-done
+	# ======================================================================
+	# Starting MVM simulator
+	# ======================================================================
+	#sendFPScmd "setval simmvmgpu-${CACAO_LOOPNUMBER}.procinfo.triggerdelay ${TRIGDELAY}"
+	sendFPScmd "confwupdate simmvmgpu-${CACAO_LOOPNUMBER}"
+	sendFPScmd "runstart simmvmgpu-${CACAO_LOOPNUMBER}"
 
 
-if [ "$CACAO_WFSSTREAM_PROCESSED" = "ON" ]; then
-echo "Processed WFS stream -> no scaling"
-
-rm -f ${MILK_SHM_DIR}/aol${CACAO_LOOPNUMBER}_wfsim.im.shm
-echo "linking aol${CACAO_LOOPNUMBER}_linsimWFS -> aol${CACAO_LOOPNUMBER}_wfsim"
-ln -s ${MILK_SHM_DIR}/aol${CACAO_LOOPNUMBER}_linsimWFS.im.shm ${MILK_SHM_DIR}/aol${CACAO_LOOPNUMBER}_wfsim.im.shm
-
-else
-# ======================================================================
-# Starting WFC camera simulator
-# ======================================================================
-
-if [ -f "simLHS/wfsdark.fits" ]; then
-milk-FITS2shm "simLHS/wfsdark.fits" aol${CACAO_LOOPNUMBER}_simwfsdark
-fi
-
-sendFPScmd "setval wfscamsim-${CACAO_LOOPNUMBER}.wfscamim ${CACAO_WFSSTREAMSIM}"
-
-FLUX=${CACAO_FPS_wfscamsim_fluxtotal:-10000000}
-sendFPScmd "setval wfscamsim-${CACAO_LOOPNUMBER}.fluxtotal ${FLUX}"
-
-camRON=${CACAO_FPS_wfscamsim_camRON:-3}
-sendFPScmd "setval wfscamsim-${CACAO_LOOPNUMBER}.camRON ${camRON}"
-
-sendFPScmd "confwupdate wfscamsim-${CACAO_LOOPNUMBER}"
-sendFPScmd "runstart wfscamsim-${CACAO_LOOPNUMBER}"
+	# WAIT for aolX_linsimWFS to appear
+	filename="${MILK_SHM_DIR}/aol${CACAO_LOOPNUMBER}_linsimWFS.im.shm"
+	echo "Waiting for file ${filename} ..."
+	until [ -f "$filename" ]
+	do
+		sleep 0.1
+	done
 
 
-if [ $WaitForCompletion == "1" ]; then
-# WAIT for aolX_wfsim to appear
-filename="${MILK_SHM_DIR}/aol${CACAO_LOOPNUMBER}_wfsim.im.shm"
-echo "Waiting for file ${filename} ..."
-until [ -f "$filename" ]
-do
-     sleep 0.1
-done
-fi
+	if [ "$CACAO_WFSSTREAM_PROCESSED" = "ON" ]; then
+		echo "Processed WFS stream -> no scaling"
+
+		rm -f ${MILK_SHM_DIR}/aol${CACAO_LOOPNUMBER}_wfsim.im.shm
+		echo "linking aol${CACAO_LOOPNUMBER}_linsimWFS -> aol${CACAO_LOOPNUMBER}_wfsim"
+		ln -s ${MILK_SHM_DIR}/aol${CACAO_LOOPNUMBER}_linsimWFS.im.shm ${MILK_SHM_DIR}/aol${CACAO_LOOPNUMBER}_wfsim.im.shm
+	else
+		# ======================================================================
+		# Starting WFC camera simulator
+		# ======================================================================
+
+		if [ -f "simLHS/wfsdark.fits" ]; then
+			milk-FITS2shm "simLHS/wfsdark.fits" aol${CACAO_LOOPNUMBER}_simwfsdark
+		fi
+
+		sendFPScmd "setval wfscamsim-${CACAO_LOOPNUMBER}.wfscamim ${CACAO_WFSSTREAMSIM}"
+
+		FLUX=${CACAO_FPS_wfscamsim_fluxtotal:-10000000}
+		sendFPScmd "setval wfscamsim-${CACAO_LOOPNUMBER}.fluxtotal ${FLUX}"
+
+		camRON=${CACAO_FPS_wfscamsim_camRON:-3}
+		sendFPScmd "setval wfscamsim-${CACAO_LOOPNUMBER}.camRON ${camRON}"
+
+		sendFPScmd "confwupdate wfscamsim-${CACAO_LOOPNUMBER}"
+		sendFPScmd "runstart wfscamsim-${CACAO_LOOPNUMBER}"
 
 
-
-fi # end of if [ "$CACAO_WFSSTREAM_PROCESSED" = "ON" ]
+		if [ $WaitForCompletion == "1" ]; then
+		# WAIT for aolX_wfsim to appear
+		filename="${MILK_SHM_DIR}/aol${CACAO_LOOPNUMBER}_wfsim.im.shm"
+		echo "Waiting for file ${filename} ..."
+		until [ -f "$filename" ]
+		do
+			sleep 0.1
+		done
+		fi
+	fi # end of if [ "$CACAO_WFSSTREAM_PROCESSED" = "ON" ]
 
 fi # end of if [ ${ACTION} == "start" ]
 
 
 if [ ${ACTION} == "stop" ]; then
-ACTIONOK=1
-cacaomsglog "STOP"
-sendFPScmd "runstop wfscamsim-${CACAO_LOOPNUMBER}"
-sendFPScmd "runstop simmvmgpu-${CACAO_LOOPNUMBER}"
-sendFPScmd "runstop DMstreamDelay-${CACAO_DMSIMINDEX}"
+	ACTIONOK=1
+	cacaomsglog "STOP"
+	sendFPScmd "runstop wfscamsim-${CACAO_LOOPNUMBER}"
+	sendFPScmd "runstop simmvmgpu-${CACAO_LOOPNUMBER}"
+	sendFPScmd "runstop DMstreamDelay-${CACAO_DMSIMINDEX}"
 fi
 
 
 
 
 if [ ${ACTIONOK} == 0 ]; then
-echo "[$(tput setaf 1)$(tput bold) FAILED $(tput sgr0)] ACTION $ACTION undefined"
+	echo "[$(tput setaf 1)$(tput bold) FAILED $(tput sgr0)] ACTION $ACTION undefined"
+	exit 1
 fi
 
 
-cacaomsglog "EXIT"
+cacaomsglog "END"
diff --git a/AOloopControl/scripts/aorun/cacao-aorun-005-takedark b/AOloopControl/scripts/aorun/cacao-aorun-005-takedark
--- a/AOloopControl/scripts/aorun/cacao-aorun-005-takedark
+++ b/AOloopControl/scripts/aorun/cacao-aorun-005-takedark
@@ -34,9 +34,9 @@ streamcheckOK="OK"
 checkstream aol${CACAO_LOOPNUMBER}_wfsim
 
 if [ ${streamcheckOK} == "FAIL" ]; then
-echo "[$(tput setaf 1)$(tput bold) FAILED $(tput sgr0)] stream check failed"
-cacaomsglog "ERROR streamcheck"
-exit
+	echo "[$(tput setaf 1)$(tput bold) FAILED $(tput sgr0)] stream check failed"
+	cacaomsglog "ERROR streamcheck"
+	exit 1
 fi
 
 cacaomsglog "NBframe ${NBframe}"
@@ -49,14 +49,14 @@ cacaomsglog "NBframe ${NBframe}"
 
 set +u
 if [ -z ${CACAO_FPSPROC_WFSCAMSIM+x} ]; then
-echo "CACAO_FPSPROC_WFSCAMSIM does not exist"
+	echo "CACAO_FPSPROC_WFSCAMSIM does not exist"
 else
 
 if [ $CACAO_FPSPROC_WFSCAMSIM = "ON" ]; then
-echo "CACAO_FPSPROC_WFSCAMSIM set -> simulator"
-sendFPScmd "setval wfscamsim-${CACAO_LOOPNUMBER}.fluxtotal 0.0"
+	echo "CACAO_FPSPROC_WFSCAMSIM set -> simulator"
+	sendFPScmd "setval wfscamsim-${CACAO_LOOPNUMBER}.fluxtotal 0.0"
 else
-echo "CACAO_FPSPROC_WFSCAMSIM not set -> no simulator"
+	echo "CACAO_FPSPROC_WFSCAMSIM not set -> no simulator"
 fi
 
 fi
@@ -107,16 +107,14 @@ ln -s ${MILK_SHM_DIR}/aol${CACAO_LOOPNUMBER}_wfsdarkraw.im.shm ${MILK_SHM_DIR}/a
 set +u
 
 if [ -z ${CACAO_FPSPROC_WFSCAMSIM+x} ]; then
-echo "CACAO_FPSPROC_WFSCAMSIM does not exist"
+	echo "CACAO_FPSPROC_WFSCAMSIM does not exist"
 else
-
-if [ $CACAO_FPSPROC_WFSCAMSIM = "ON" ]; then
-FLUX=${CACAO_FPS_wfscamsim_fluxtotal:-100000}
-sendFPScmd "setval wfscamsim-${CACAO_LOOPNUMBER}.fluxtotal ${FLUX}"
-else
-echo "CACAO_FPSPROC_WFSCAMSIM not set -> no simulator"
-fi
-
+	if [ $CACAO_FPSPROC_WFSCAMSIM = "ON" ]; then
+		FLUX=${CACAO_FPS_wfscamsim_fluxtotal:-100000}
+		sendFPScmd "setval wfscamsim-${CACAO_LOOPNUMBER}.fluxtotal ${FLUX}"
+	else
+		echo "CACAO_FPSPROC_WFSCAMSIM not set -> no simulator"
+	fi
 fi
 
 set -u
diff --git a/AOloopControl/scripts/aorun/cacao-aorun-020-mlat b/AOloopControl/scripts/aorun/cacao-aorun-020-mlat
--- a/AOloopControl/scripts/aorun/cacao-aorun-020-mlat
+++ b/AOloopControl/scripts/aorun/cacao-aorun-020-mlat
@@ -36,9 +36,10 @@ FPScheckOK="OK"
 checkFPSON CACAO_FPSPROC_MLAT ${CACAO_FPSPROC_MLAT}
 
 if [ ${FPScheckOK} == "FAIL" ]; then
-echo "[$(tput setaf 1)$(tput bold) FAILED $(tput sgr0)] FPS check failed"
-cacaomsglog "ERROR FPScheck"
-errexit=1
+	echo "[$(tput setaf 1)$(tput bold) FAILED $(tput sgr0)] FPS check failed"
+	cacaomsglog "ERROR FPScheck"
+	errexit=1
+	exit 1
 fi
 
 
@@ -47,14 +48,15 @@ streamcheckOK="OK"
 checkstream aol${CACAO_LOOPNUMBER}_wfsim
 
 if [ ${streamcheckOK} == "FAIL" ]; then
-echo "[$(tput setaf 1)$(tput bold) FAILED $(tput sgr0)] stream check failed"
-cacaomsglog "ERROR streamcheck"
-errexit=1
+	echo "[$(tput setaf 1)$(tput bold) FAILED $(tput sgr0)] stream check failed"
+	cacaomsglog "ERROR streamcheck"
+	errexit=1
+	exit 1
 fi
 
 
 if [ $errexit = 1 ]; then
-exit
+	exit 1
 fi
 
 
@@ -68,12 +70,12 @@ sendFPScmd "confwupdate mlat-${CACAO_LOOPNUMBER}"
 sendFPScmd "runstart mlat-${CACAO_LOOPNUMBER}"
 
 if [ $WaitForCompletion == "1" ]; then
-echo "Waiting for completion ..."
-pOK=1
-while [ $pOK -gt 0 ]; do
-	sleep 0.2
-	pOK=$(ps -alx| grep mlat-${CACAO_LOOPNUMBER} | grep RUNSTART | wc -l)
-done
+	echo "Waiting for completion ..."
+	pOK=1
+	while [ $pOK -gt 0 ]; do
+		sleep 0.2
+		pOK=$(ps -alx| grep mlat-${CACAO_LOOPNUMBER} | grep RUNSTART | wc -l) || :
+	done
 fi
 
-cacaomsglog "EXIT"
+cacaomsglog "END"
diff --git a/AOloopControl/scripts/aorun/cacao-aorun-025-acqWFS b/AOloopControl/scripts/aorun/cacao-aorun-025-acqWFS
--- a/AOloopControl/scripts/aorun/cacao-aorun-025-acqWFS
+++ b/AOloopControl/scripts/aorun/cacao-aorun-025-acqWFS
@@ -11,6 +11,8 @@ MSextdescr="reads from aolX_wfsim
 Subtract dark      -> aolX_imWFS0
 Normalizes flux    -> aolX_imWFS1
 Subtract reference -> aolX_imWFS2"
+
+
 source milk-script-std-config
 source cacao-check-cacaovars
 
@@ -38,7 +40,7 @@ ACTIONOK=0
 
 
 if [ ${ACTION} == "check" ]; then
-ACTIONOK=1
+	ACTIONOK=1
 fi
 
 errexit=0
@@ -48,9 +50,9 @@ FPScheckOK="OK"
 checkFPSON CACAO_FPSPROC_ACQUWFS ${CACAO_FPSPROC_ACQUWFS}
 
 if [ ${FPScheckOK} == "FAIL" ]; then
-echo "[$(tput setaf 1)$(tput bold) FAILED $(tput sgr0)] FPS check failed"
-cacaomsglog "ERROR FPScheck"
-errexit=1
+	echo "[$(tput setaf 1)$(tput bold) FAILED $(tput sgr0)] FPS check failed"
+	cacaomsglog "ERROR FPScheck"
+	errexit=1
 fi
 
 
@@ -59,14 +61,14 @@ streamcheckOK="OK"
 checkstream aol${CACAO_LOOPNUMBER}_wfsim
 
 if [ ${streamcheckOK} == "FAIL" ]; then
-echo "[$(tput setaf 1)$(tput bold) FAILED $(tput sgr0)] stream check failed"
-cacaomsglog "ERROR streamcheck"
-errexit=1
+	echo "[$(tput setaf 1)$(tput bold) FAILED $(tput sgr0)] stream check failed"
+	cacaomsglog "ERROR streamcheck"
+	errexit=1
 fi
 
 
 if [ $errexit = 1 ]; then
-exit
+	exit 1
 fi
 
 
@@ -83,18 +85,18 @@ ACTIONOK=1
 cacaomsglog "START"
 
 if [ "$CACAO_WFSSTREAM_PROCESSED" = "ON" ]; then
-echo "Processed WFS stream -> no scaling"
-cacaomsglog "INFO CACAO_WFSSTREAM_PROCESSED ON"
-sendFPScmd "setval acquWFS-${CACAO_LOOPNUMBER}.comp.WFSnormalize OFF"
-sendFPScmd "setval acquWFS-${CACAO_LOOPNUMBER}.comp.WFSrefsub OFF"
-sendFPScmd "setval acquWFS-${CACAO_LOOPNUMBER}.comp.WFSsigav ON"
-sendFPScmd "setval acquWFS-${CACAO_LOOPNUMBER}.comp.WFSrefc ON"
+	echo "Processed WFS stream -> no scaling"
+	cacaomsglog "INFO CACAO_WFSSTREAM_PROCESSED ON"
+	sendFPScmd "setval acquWFS-${CACAO_LOOPNUMBER}.comp.WFSnormalize OFF"
+	sendFPScmd "setval acquWFS-${CACAO_LOOPNUMBER}.comp.WFSrefsub OFF"
+	sendFPScmd "setval acquWFS-${CACAO_LOOPNUMBER}.comp.WFSsigav ON"
+	sendFPScmd "setval acquWFS-${CACAO_LOOPNUMBER}.comp.WFSrefc ON"
 else
-cacaomsglog "INFO CACAO_WFSSTREAM_PROCESSED OFF"
-sendFPScmd "setval acquWFS-${CACAO_LOOPNUMBER}.comp.WFSnormalize ON"
-sendFPScmd "setval acquWFS-${CACAO_LOOPNUMBER}.comp.WFSrefsub ON"
-sendFPScmd "setval acquWFS-${CACAO_LOOPNUMBER}.comp.WFSsigav ON"
-sendFPScmd "setval acquWFS-${CACAO_LOOPNUMBER}.comp.WFSrefc ON"
+	cacaomsglog "INFO CACAO_WFSSTREAM_PROCESSED OFF"
+	sendFPScmd "setval acquWFS-${CACAO_LOOPNUMBER}.comp.WFSnormalize ON"
+	sendFPScmd "setval acquWFS-${CACAO_LOOPNUMBER}.comp.WFSrefsub ON"
+	sendFPScmd "setval acquWFS-${CACAO_LOOPNUMBER}.comp.WFSsigav ON"
+	sendFPScmd "setval acquWFS-${CACAO_LOOPNUMBER}.comp.WFSrefc ON"
 fi
 
 cacaomsglog "confwupdate"
@@ -104,14 +106,13 @@ sendFPScmd "runstart acquWFS-${CACAO_LOOPNUMBER}"
 
 
 if [ $WaitForCompletion == "1" ]; then
-sname="aol${CACAO_LOOPNUMBER}_imWFS2"
-echo "Waiting for stream ${sname}"
-until [ -f "${MILK_SHM_DIR}/${sname}.im.shm" ]
-do
-     sleep 0.1
-done
-fi
-
+	sname="aol${CACAO_LOOPNUMBER}_imWFS2"
+	echo "Waiting for stream ${sname}"
+	until [ -f "${MILK_SHM_DIR}/${sname}.im.shm" ]
+		do
+			sleep 0.1
+		done
+	fi
 fi
 
 
@@ -119,15 +120,15 @@ fi
 
 
 if [ ${ACTION} == "stop" ]; then
-ACTIONOK=1
-cacaomsglog "STOP"
-sendFPScmd "runstop acquWFS-${CACAO_LOOPNUMBER}"
-
+	ACTIONOK=1
+	cacaomsglog "STOP"
+	sendFPScmd "runstop acquWFS-${CACAO_LOOPNUMBER}"
 fi
 
 
 
 
 if [ ${ACTIONOK} == 0 ]; then
-echo "[$(tput setaf 1)$(tput bold) FAILED $(tput sgr0)] ACTION $ACTION undefined"
+	echo "[$(tput setaf 1)$(tput bold) FAILED $(tput sgr0)] ACTION $ACTION undefined"
+	exit 1
 fi
diff --git a/AOloopControl/scripts/aorun/cacao-aorun-026-takeref b/AOloopControl/scripts/aorun/cacao-aorun-026-takeref
--- a/AOloopControl/scripts/aorun/cacao-aorun-026-takeref
+++ b/AOloopControl/scripts/aorun/cacao-aorun-026-takeref
@@ -26,9 +26,9 @@ streamcheckOK="OK"
 checkstream aol${CACAO_LOOPNUMBER}_imWFS2
 
 if [ ${streamcheckOK} == "FAIL" ]; then
-echo "[$(tput setaf 1)$(tput bold) FAILED $(tput sgr0)] stream check failed"
-cacaomsglog "ERROR streamcheck"
-exit
+	echo "[$(tput setaf 1)$(tput bold) FAILED $(tput sgr0)] stream check failed"
+	cacaomsglog "ERROR streamcheck"
+	exit 1
 fi
 
 cacaomsglog "NBframe ${NBframe}"
@@ -48,4 +48,4 @@ listim
 exitCLI
 EOF
 
-cacaomsglog "EXIT"
+cacaomsglog "END"
diff --git a/AOloopControl/scripts/aorun/cacao-aorun-030-acqlinResp b/AOloopControl/scripts/aorun/cacao-aorun-030-acqlinResp
--- a/AOloopControl/scripts/aorun/cacao-aorun-030-acqlinResp
+++ b/AOloopControl/scripts/aorun/cacao-aorun-030-acqlinResp
@@ -52,9 +52,10 @@ checkFPSON CACAO_FPSPROC_ACQUWFS ${CACAO_FPSPROC_ACQUWFS}
 checkFPSON CACAO_FPSPROC_ACQLINZRM ${CACAO_FPSPROC_MEASURELINRESP}
 
 if [ ${FPScheckOK} == "FAIL" ]; then
-echo "[$(tput setaf 1)$(tput bold) FAILED $(tput sgr0)] FPS check failed"
-cacaomsglog "ERROR FPScheck"
-errexit=1
+	echo "[$(tput setaf 1)$(tput bold) FAILED $(tput sgr0)] FPS check failed"
+	cacaomsglog "ERROR FPScheck"
+	errexit=1
+	exit 1
 fi
 
 
@@ -65,14 +66,15 @@ checkstream aol${CACAO_LOOPNUMBER}_imWFS1
 checkstream aol${CACAO_LOOPNUMBER}_imWFS2
 
 if [ ${streamcheckOK} == "FAIL" ]; then
-echo "[$(tput setaf 1)$(tput bold) FAILED $(tput sgr0)] stream check failed"
-cacaomsglog "ERROR streamcheck"
-errexit=1
+	echo "[$(tput setaf 1)$(tput bold) FAILED $(tput sgr0)] stream check failed"
+	cacaomsglog "ERROR streamcheck"
+	errexit=1
+	exit 1
 fi
 
 
 if [ $errexit = 1 ]; then
-exit
+	exit 1
 fi
 
 
@@ -96,7 +98,7 @@ sendFPScmd "confwupdate measlinresp-${CACAO_LOOPNUMBER}"
 sendFPScmd "runstart measlinresp-${CACAO_LOOPNUMBER}"
 cacaomsglog "START"
 
-pwd
+
 rm -f ./conf/RMmodesDM/RMmodesDM.fits
 ln -s $(pwd)/conf/RMmodesDM/${DMmodeCname}.fits ./conf/RMmodesDM/RMmodesDM.fits
 
@@ -108,8 +110,8 @@ echo "Waiting for completion ..."
 pOK=1
 while [ $pOK -gt 0 ]; do
 	sleep 0.2
-	pOK=$(ps -alx| grep measlinresp-${CACAO_LOOPNUMBER} | grep RUNSTART | wc -l)
+	pOK=$(ps -alx| grep measlinresp-${CACAO_LOOPNUMBER} | grep RUNSTART | wc -l) || :
 done
 fi
 
-cacaomsglog "EXIT"
+cacaomsglog "END"
diff --git a/AOloopControl/scripts/aorun/cacao-aorun-031-acqzRM b/AOloopControl/scripts/aorun/cacao-aorun-031-acqzRM
--- a/AOloopControl/scripts/aorun/cacao-aorun-031-acqzRM
+++ b/AOloopControl/scripts/aorun/cacao-aorun-031-acqzRM
@@ -4,9 +4,10 @@
 # See template milk-scriptexample in module milk_module_example for template and instructions
 
 # script 1-line description
-MSdescr="AO loop execution script"
+MSdescr="Acquire zonal response matrix"
 
-MSextdescr="AO loop script"
+MSextdescr="Acquire zonal response matrix"
+
 source milk-script-std-config
 source cacao-check-cacaovars
 
@@ -22,7 +23,7 @@ ACTIONOK=0
 
 
 if [ ${ACTION} == "check" ]; then
-ACTIONOK=1
+	ACTIONOK=1
 fi
 
 
@@ -34,8 +35,9 @@ checkFPSON CACAO_FPSPROC_ACQUWFS ${CACAO_FPSPROC_ACQUWFS}
 checkFPSON CACAO_FPSPROC_ACQLINZRM ${CACAO_FPSPROC_ACQLINZRM}
 
 if [ ${FPScheckOK} == "FAIL" ]; then
-echo "[$(tput setaf 1)$(tput bold) FAILED $(tput sgr0)] FPS check failed"
-errexit=1
+	echo "[$(tput setaf 1)$(tput bold) FAILED $(tput sgr0)] FPS check failed"
+	errexit=1
+	exit 1
 fi
 
 
@@ -46,13 +48,14 @@ checkstream aol${CACAO_LOOPNUMBER}_imWFS1
 checkstream aol${CACAO_LOOPNUMBER}_imWFS2
 
 if [ ${streamcheckOK} == "FAIL" ]; then
-echo "[$(tput setaf 1)$(tput bold) FAILED $(tput sgr0)] stream check failed"
-errexit=1
+	echo "[$(tput setaf 1)$(tput bold) FAILED $(tput sgr0)] stream check failed"
+	errexit=1
+	exit 1
 fi
 
 
 if [ $errexit = 1 ]; then
-exit
+	exit 1
 fi
 
 
@@ -63,16 +66,15 @@ fi
 
 
 if [ ${ACTION} == "start" ]; then
-ACTIONOK=1
+	ACTIONOK=1
 
-# ======================================================================
-# acquWFS
-# ======================================================================
-sendFPScmd "setval acqlin_zRM-${CACAO_LOOPNUMBER}.AOloopindex ${CACAO_LOOPNUMBER}"
+	# ======================================================================
+	# acquWFS
+	# ======================================================================
+	sendFPScmd "setval acqlin_zRM-${CACAO_LOOPNUMBER}.AOloopindex ${CACAO_LOOPNUMBER}"
 
-sendFPScmd "confwupdate acqlin_zRM-${CACAO_LOOPNUMBER}"
-sendFPScmd "runstart acqlin_zRM-${CACAO_LOOPNUMBER}"
-
+	sendFPScmd "confwupdate acqlin_zRM-${CACAO_LOOPNUMBER}"
+	sendFPScmd "runstart acqlin_zRM-${CACAO_LOOPNUMBER}"
 fi
 
 
@@ -81,5 +83,6 @@ fi
 
 
 if [ ${ACTIONOK} == 0 ]; then
-echo "[$(tput setaf 1)$(tput bold) FAILED $(tput sgr0)] ACTION $ACTION undefined"
+	echo "[$(tput setaf 1)$(tput bold) FAILED $(tput sgr0)] ACTION $ACTION undefined"
+	exit 1
 fi
diff --git a/AOloopControl/scripts/aorun/cacao-aorun-040-compfCM b/AOloopControl/scripts/aorun/cacao-aorun-040-compfCM
--- a/AOloopControl/scripts/aorun/cacao-aorun-040-compfCM
+++ b/AOloopControl/scripts/aorun/cacao-aorun-040-compfCM
@@ -22,13 +22,15 @@ FPScheckOK="OK"
 checkFPSON CACAO_FPSPROC_COMPFCM ${CACAO_FPSPROC_COMPFCM}
 
 if [ ${FPScheckOK} == "FAIL" ]; then
-echo "[$(tput setaf 1)$(tput bold) FAILED $(tput sgr0)] FPS check failed"
-errexit=1
+	echo "[$(tput setaf 1)$(tput bold) FAILED $(tput sgr0)] FPS check failed"
+	cacaomsglog "ERROR FPS check"
+	errexit=1
+	exit 1
 fi
 
 
 if [ $errexit = 1 ]; then
-exit
+	exit 1
 fi
 
 
@@ -42,3 +44,5 @@ sendFPScmd "setval compfCM-${CACAO_LOOPNUMBER}.upAlign ON"
 
 sendFPScmd "confwupdate compfCM-${CACAO_LOOPNUMBER}"
 sendFPScmd "runstart compfCM-${CACAO_LOOPNUMBER}"
+
+cacaomsglog "END"
diff --git a/AOloopControl/scripts/aorun/cacao-aorun-041-loadCM b/AOloopControl/scripts/aorun/cacao-aorun-041-loadCM
--- a/AOloopControl/scripts/aorun/cacao-aorun-041-loadCM
+++ b/AOloopControl/scripts/aorun/cacao-aorun-041-loadCM
@@ -50,8 +50,8 @@ checkFile ${CMDMfname}
 checkFile ${CMWFSfname}
 
 if [ ${EXITSTATUS} = 1 ]; then
-echo "missing file - cannot proceed"
-exit
+	echo "missing file - cannot proceed"
+	exit 1
 fi
 
 
@@ -63,20 +63,20 @@ fi
 FPScheckOK="OK"
 checkFPSON CACAO_FPSPROC_MVMGPU_CMODEVAL2DM ${CACAO_FPSPROC_MVMGPU_CMODEVAL2DM}
 if [ ${FPScheckOK} == "OK" ]; then
-sendFPScmd "runstop mvalC2dm-${CACAO_LOOPNUMBER}"
+	sendFPScmd "runstop mvalC2dm-${CACAO_LOOPNUMBER}"
 fi
 
 FPScheckOK="OK"
 checkFPSON CACAO_FPSPROC_MODALFILTERING ${CACAO_FPSPROC_MODALFILTERING}
 if [ ${FPScheckOK} == "OK" ]; then
-sendFPScmd "runstop mfilt-${CACAO_LOOPNUMBER}"
+	sendFPScmd "runstop mfilt-${CACAO_LOOPNUMBER}"
 fi
 
 
 FPScheckOK="OK"
 checkFPSON CACAO_FPSPROC_MVMGPU_WFS2CMODEVAL ${CACAO_FPSPROC_MVMGPU_WFS2CMODEVAL}
 if [ ${FPScheckOK} == "OK" ]; then
-sendFPScmd "runstop wfs2cmodeval-${CACAO_LOOPNUMBER}"
+	sendFPScmd "runstop wfs2cmodeval-${CACAO_LOOPNUMBER}"
 fi
 
 
@@ -85,12 +85,12 @@ fi
 
 
 if [ ${UpdateFiles} = 1 ]; then
-echo "Updating files"
+	echo "Updating files"
 
-ln -sf ${PWD}/${RMDMfname} ${RMDMfname0}
-ln -sf ${PWD}/${RMWFSfname} ${RMWFSfname0}
-ln -sf ${PWD}/${CMDMfname} ${CMDMfname0}
-ln -sf ${PWD}/${CMWFSfname} ${CMWFSfname0}
+	ln -sf ${PWD}/${RMDMfname} ${RMDMfname0}
+	ln -sf ${PWD}/${RMWFSfname} ${RMWFSfname0}
+	ln -sf ${PWD}/${CMDMfname} ${CMDMfname0}
+	ln -sf ${PWD}/${CMWFSfname} ${CMWFSfname0}
 
 fi
 
diff --git a/AOloopControl/scripts/aorun/cacao-aorun-041-saveCM b/AOloopControl/scripts/aorun/cacao-aorun-041-saveCM
--- a/AOloopControl/scripts/aorun/cacao-aorun-041-saveCM
+++ b/AOloopControl/scripts/aorun/cacao-aorun-041-saveCM
@@ -49,8 +49,8 @@ checkFile ${CMDMfname0}
 checkFile ${CMWFSfname0}
 
 if [ ${EXITSTATUS} = 1 ]; then
-echo "missing file - cannot proceed"
-exit
+	echo "missing file - cannot proceed"
+	exit 1
 fi
 
 
@@ -61,3 +61,4 @@ cp ${CMDMfname0} ${CMDMfname}
 cp ${CMWFSfname0} ${CMWFSfname}
 
 
+cacaomsglog "END"
diff --git a/AOloopControl/scripts/aorun/cacao-aorun-050-wfs2cmval b/AOloopControl/scripts/aorun/cacao-aorun-050-wfs2cmval
--- a/AOloopControl/scripts/aorun/cacao-aorun-050-wfs2cmval
+++ b/AOloopControl/scripts/aorun/cacao-aorun-050-wfs2cmval
@@ -21,7 +21,7 @@ ACTION="${inputMSargARRAY[0]}"
 ACTIONOK=0
 
 if [ ${ACTION} == "check" ]; then
-ACTIONOK=1
+	ACTIONOK=1
 fi
 
 
@@ -30,35 +30,34 @@ FPScheckOK="OK"
 checkFPSON CACAO_FPSPROC_MVMGPU_WFS2CMODEVAL ${CACAO_FPSPROC_MVMGPU_WFS2CMODEVAL}
 
 if [ ${FPScheckOK} == "FAIL" ]; then
-echo "[$(tput setaf 1)$(tput bold) FAILED $(tput sgr0)] FPS check failed"
-cacaomsglog "ERROR failed FPS check"
-exit
+	echo "[$(tput setaf 1)$(tput bold) FAILED $(tput sgr0)] FPS check failed"
+	cacaomsglog "ERROR failed FPS check"
+	exit 1
 fi
 
 
 if [ ${ACTION} == "start" ]; then
-ACTIONOK=1
+	ACTIONOK=1
 
-cacaomsglog "START"
-sendFPScmd "confwupdate wfs2cmodeval-${CACAO_LOOPNUMBER}"
-sendFPScmd "runstart wfs2cmodeval-${CACAO_LOOPNUMBER}"
-
+	cacaomsglog "START"
+	sendFPScmd "confwupdate wfs2cmodeval-${CACAO_LOOPNUMBER}"
+	sendFPScmd "runstart wfs2cmodeval-${CACAO_LOOPNUMBER}"
 fi
 
 
 
 if [ ${ACTION} == "stop" ]; then
-ACTIONOK=1
-
-cacaomsglog "STOP"
-sendFPScmd "runstop wfs2cmodeval-${CACAO_LOOPNUMBER}"
+	ACTIONOK=1
+	cacaomsglog "STOP"
+	sendFPScmd "runstop wfs2cmodeval-${CACAO_LOOPNUMBER}"
 fi
 
 
 
 if [ ${ACTIONOK} == 0 ]; then
-cacaomsglog "ERROR undefined action"
-echo "[$(tput setaf 1)$(tput bold) FAILED $(tput sgr0)] ACTION $ACTION undefined"
+	cacaomsglog "ERROR undefined action"
+	echo "[$(tput setaf 1)$(tput bold) FAILED $(tput sgr0)] ACTION $ACTION undefined"
+	exit 1
 fi
 
 cacaomsglog "END"
diff --git a/AOloopControl/scripts/aorun/cacao-aorun-060-mfilt b/AOloopControl/scripts/aorun/cacao-aorun-060-mfilt
--- a/AOloopControl/scripts/aorun/cacao-aorun-060-mfilt
+++ b/AOloopControl/scripts/aorun/cacao-aorun-060-mfilt
@@ -21,7 +21,7 @@ ACTION="${inputMSargARRAY[0]}"
 ACTIONOK=0
 
 if [ ${ACTION} == "check" ]; then
-ACTIONOK=1
+	ACTIONOK=1
 fi
 
 # Checking FPS
@@ -29,38 +29,38 @@ FPScheckOK="OK"
 checkFPSON CACAO_FPSPROC_MODALFILTERING ${CACAO_FPSPROC_MODALFILTERING}
 
 if [ ${FPScheckOK} == "FAIL" ]; then
-echo "[$(tput setaf 1)$(tput bold) FAILED $(tput sgr0)] FPS check failed"
-cacaomsglog "ERROR FPScheck failed"
-exit
+	echo "[$(tput setaf 1)$(tput bold) FAILED $(tput sgr0)] FPS check failed"
+	cacaomsglog "ERROR FPScheck"
+	exit 1
 fi
 
 
 
 
 if [ ${ACTION} == "start" ]; then
-ACTIONOK=1
-cacaomsglog "START"
-sendFPScmd "setval mfilt-${CACAO_LOOPNUMBER}.AOloopindex ${CACAO_LOOPNUMBER}"
-sendFPScmd "setval mfilt-${CACAO_LOOPNUMBER}.comp.latencyhardwfr ${CACAO_LATENCYHARDWFR}"
-sendFPScmd "setval mfilt-${CACAO_LOOPNUMBER}.comp.OLmodes ON"
-sendFPScmd "setval mfilt-${CACAO_LOOPNUMBER}.comp.tbuff ON"
-sendFPScmd "confwupdate mfilt-${CACAO_LOOPNUMBER}"
-sendFPScmd "runstart mfilt-${CACAO_LOOPNUMBER}"
-
+	ACTIONOK=1
+	cacaomsglog "START"
+	sendFPScmd "setval mfilt-${CACAO_LOOPNUMBER}.AOloopindex ${CACAO_LOOPNUMBER}"
+	sendFPScmd "setval mfilt-${CACAO_LOOPNUMBER}.comp.latencyhardwfr ${CACAO_LATENCYHARDWFR}"
+	sendFPScmd "setval mfilt-${CACAO_LOOPNUMBER}.comp.OLmodes ON"
+	sendFPScmd "setval mfilt-${CACAO_LOOPNUMBER}.comp.tbuff ON"
+	sendFPScmd "confwupdate mfilt-${CACAO_LOOPNUMBER}"
+	sendFPScmd "runstart mfilt-${CACAO_LOOPNUMBER}"
 fi
 
 
 if [ ${ACTION} == "stop" ]; then
-ACTIONOK=1
-cacaomsglog "STOP"
-sendFPScmd "runstop mfilt-${CACAO_LOOPNUMBER}"
+	ACTIONOK=1
+	cacaomsglog "STOP"
+	sendFPScmd "runstop mfilt-${CACAO_LOOPNUMBER}"
 fi
 
 
 
 
 if [ ${ACTIONOK} == 0 ]; then
-echo "[$(tput setaf 1)$(tput bold) FAILED $(tput sgr0)] ACTION $ACTION undefined"
+	echo "[$(tput setaf 1)$(tput bold) FAILED $(tput sgr0)] ACTION $ACTION undefined"
+	cacaomsglog "ERROR ACTION undefined"
 fi
 
 cacaomsglog "END"
diff --git a/AOloopControl/scripts/aorun/cacao-aorun-070-cmval2dm b/AOloopControl/scripts/aorun/cacao-aorun-070-cmval2dm
--- a/AOloopControl/scripts/aorun/cacao-aorun-070-cmval2dm
+++ b/AOloopControl/scripts/aorun/cacao-aorun-070-cmval2dm
@@ -9,7 +9,6 @@ MSdescr="Expand modal values to DM map"
 MSextdescr="Modal values to DM map"
 
 source milk-script-std-config
-
 source cacao-check-cacaovars
 
 MSarg+=( "action:string:action (start/stop/check)" )
@@ -32,34 +31,34 @@ FPScheckOK="OK"
 checkFPSON CACAO_FPSPROC_MVMGPU_CMODEVAL2DM ${CACAO_FPSPROC_MVMGPU_CMODEVAL2DM}
 
 if [ ${FPScheckOK} == "FAIL" ]; then
-echo "[$(tput setaf 1)$(tput bold) FAILED $(tput sgr0)] FPS check failed"
-cacaomsglog "ERROR FPScheck failed"
-exit
+	echo "[$(tput setaf 1)$(tput bold) FAILED $(tput sgr0)] FPS check failed"
+	cacaomsglog "ERROR FPScheck failed"
+	exit 1
 fi
 
 
 
 
 if [ ${ACTION} == "start" ]; then
-ACTIONOK=1
-cacaomsglog "START"
-sendFPScmd "confwupdate mvalC2dm-${CACAO_LOOPNUMBER}"
-sendFPScmd "runstart mvalC2dm-${CACAO_LOOPNUMBER}"
-
+	ACTIONOK=1
+	cacaomsglog "START"
+	sendFPScmd "confwupdate mvalC2dm-${CACAO_LOOPNUMBER}"
+	sendFPScmd "runstart mvalC2dm-${CACAO_LOOPNUMBER}"
 fi
 
 
 
 if [ ${ACTION} == "stop" ]; then
-ACTIONOK=1
-cacaomsglog "STOP"
-sendFPScmd "runstop mvalC2dm-${CACAO_LOOPNUMBER}"
+	ACTIONOK=1
+	cacaomsglog "STOP"
+	sendFPScmd "runstop mvalC2dm-${CACAO_LOOPNUMBER}"
 fi
 
 
 
 if [ ${ACTIONOK} == 0 ]; then
-echo "[$(tput setaf 1)$(tput bold) FAILED $(tput sgr0)] ACTION $ACTION undefined"
+	echo "[$(tput setaf 1)$(tput bold) FAILED $(tput sgr0)] ACTION $ACTION undefined"
+	exit 1
 fi
 
 cacaomsglog "END"
diff --git a/AOloopControl/scripts/aorun/cacao-aorun-071-zpo b/AOloopControl/scripts/aorun/cacao-aorun-071-zpo
--- a/AOloopControl/scripts/aorun/cacao-aorun-071-zpo
+++ b/AOloopControl/scripts/aorun/cacao-aorun-071-zpo
@@ -7,19 +7,21 @@
 MSdescr="Zero Point Offset (zpo) MVM"
 
 MSextdescr="convert dmzpo to wfszpo"
+
 source milk-script-std-config
 source cacao-check-cacaovars
 
 
 MSarg+=( "action:string:action (start/stop/check)" )
 source milk-argparse
+
 ACTION="${inputMSargARRAY[0]}"
 
 
 ACTIONOK=0
 
 if [ ${ACTION} == "check" ]; then
-ACTIONOK=1
+	ACTIONOK=1
 fi
 
 # Checking FPS
@@ -28,36 +30,32 @@ checkFPSON CACAO_FPSPROC_MODALFILTERING ${CACAO_FPSPROC_MODALFILTERING}
 checkFPSON CACAO_FPSPROC_MVMGPU_ZPO ${CACAO_FPSPROC_MVMGPU_ZPO}
 
 if [ ${FPScheckOK} == "FAIL" ]; then
-echo "[$(tput setaf 1)$(tput bold) FAILED $(tput sgr0)] FPS check failed"
-exit
+	echo "[$(tput setaf 1)$(tput bold) FAILED $(tput sgr0)] FPS check failed"
+	exit 1
 fi
 
 
 
 
 if [ ${ACTION} == "start" ]; then
-ACTIONOK=1
+	ACTIONOK=1
 
-# ${CACAO_DMINDEX}
-
-# load zresp to shared memory
-milk-FITS2shm "conf/RMmodesWFS/zrespM-H.fits" aol${CACAO_LOOPNUMBER}_zrespM
-sendFPScmd "setval DMch2disp-${CACAO_DMINDEX}.zpoffset.enable ON"
-sendFPScmd "confwupdate zpo-${CACAO_LOOPNUMBER}"
-sendFPScmd "runstart zpo-${CACAO_LOOPNUMBER}"
-
+	# load zresp to shared memory
+	milk-FITS2shm "conf/RMmodesWFS/zrespM-H.fits" aol${CACAO_LOOPNUMBER}_zrespM
+	sendFPScmd "setval DMch2disp-${CACAO_DMINDEX}.zpoffset.enable ON"
+	sendFPScmd "confwupdate zpo-${CACAO_LOOPNUMBER}"
+	sendFPScmd "runstart zpo-${CACAO_LOOPNUMBER}"
 fi
 
 
 if [ ${ACTION} == "stop" ]; then
-ACTIONOK=1
-sendFPScmd "setval DMch2disp-${CACAO_DMINDEX}.zpoffset.enable OFF"
-sendFPScmd "runstop zpo-${CACAO_LOOPNUMBER}"
+	ACTIONOK=1
+	sendFPScmd "setval DMch2disp-${CACAO_DMINDEX}.zpoffset.enable OFF"
+	sendFPScmd "runstop zpo-${CACAO_LOOPNUMBER}"
 fi
 
 
-
-
 if [ ${ACTIONOK} == 0 ]; then
-echo "[$(tput setaf 1)$(tput bold) FAILED $(tput sgr0)] ACTION $ACTION undefined"
+	echo "[$(tput setaf 1)$(tput bold) FAILED $(tput sgr0)] ACTION $ACTION undefined"
+	exit 1
 fi
diff --git a/AOloopControl/scripts/aorun/cacao-aorun-080-testOL b/AOloopControl/scripts/aorun/cacao-aorun-080-testOL
--- a/AOloopControl/scripts/aorun/cacao-aorun-080-testOL
+++ b/AOloopControl/scripts/aorun/cacao-aorun-080-testOL
@@ -32,8 +32,9 @@ FPScheckOK="OK"
 checkFPSON CACAO_FPSPROC_MODALFILTERING ${CACAO_FPSPROC_MODALFILTERING}
 
 if [ ${FPScheckOK} == "FAIL" ]; then
-echo "[$(tput setaf 1)$(tput bold) FAILED $(tput sgr0)] FPS check failed"
-exit
+	echo "[$(tput setaf 1)$(tput bold) FAILED $(tput sgr0)] FPS check failed"
+	cacaomsglog "ERROR FPS check"
+	exit 1
 fi
 
 
@@ -42,9 +43,9 @@ OUTFILE="${CACAO_LOOPRUNDIR}/fps.mfilt-${CACAO_LOOPNUMBER}.datadir/cacaovars.bas
 
 # Record inodestring
 if [ -f "${OUTFILE}" ]; then
-string0="$(md5sum ${OUTFILE})"
+	string0="$(md5sum ${OUTFILE})"
 else
-string0="NULL"
+	string0="NULL"
 fi
 string1="${string0}"
 
@@ -54,16 +55,18 @@ sendFPScmd "setval mfilt-${CACAO_LOOPNUMBER}.testOL.updategain ${UPDATEGAIN}"
 sendFPScmd "setval mfilt-${CACAO_LOOPNUMBER}.testOL.enable ON"
 
 if [ $WaitForCompletion == "1" ]; then
-echo "Waiting for completion ..."
-while [ "${string0}" == "${string1}" ]; do
-	sleep 0.2
-	if [ -f "${OUTFILE}" ]; then
-		string1="$(md5sum ${OUTFILE})"
-	else
-		string1="NULL"
-	fi
-	#echo "(${string0})  <<>> (${string1})"
-	echo -n "."
-done
-echo ""
+	echo "Waiting for completion ..."
+	while [ "${string0}" == "${string1}" ]; do
+		sleep 0.2
+		if [ -f "${OUTFILE}" ]; then
+			string1="$(md5sum ${OUTFILE})"
+		else
+			string1="NULL"
+		fi
+		#echo "(${string0})  <<>> (${string1})"
+		echo -n "."
+	done
+	echo ""
 fi
+
+cacaomsglog "END"
diff --git a/AOloopControl/scripts/aorun/cacao-aorun-100-DMturb b/AOloopControl/scripts/aorun/cacao-aorun-100-DMturb
--- a/AOloopControl/scripts/aorun/cacao-aorun-100-DMturb
+++ b/AOloopControl/scripts/aorun/cacao-aorun-100-DMturb
@@ -8,74 +8,94 @@ MSdescr="Inject turbulence on DM"
 
 MSextdescr="Inject turbulence on DM channel 10
 Commands: start, stop, on, off"
+
+
 source milk-script-std-config
 source cacao-check-cacaovars
 
+RequiredFiles=(DMINDEX)
 
 MSarg+=( "action:string:action (start/stop/check)" )
 source milk-argparse
 ACTION="${inputMSargARRAY[0]}"
 
 
+if [ -f DMINDEX ]; then
+    DMINDEX=$( head -1 DMINDEX )
+else
+	cacaomsglog "Error: no DMINDEX file. Are we running this from the correct directory ?"
+    exit 1
+fi
+
+
+
 ACTIONOK=0
 
 if [ ${ACTION} == "check" ]; then
-ACTIONOK=1
+	ACTIONOK=1
 fi
 
 # Checking FPS
 FPScheckOK="OK"
 checkFPSON CACAO_FPSPROC_DMATMTURB ${CACAO_FPSPROC_DMATMTURB}
 
+
 if [ ${FPScheckOK} == "FAIL" ]; then
-echo "[$(tput setaf 1)$(tput bold) FAILED $(tput sgr0)] FPS check failed"
-exit
+	echo "[$(tput setaf 1)$(tput bold) FAILED $(tput sgr0)] FPS check failed"
+	cacaomsglog "ERROR FPScheck"
+	exit 1
 fi
 
 
 TURBFILE="conf/turbseed0.fits"
 
 if [ -f ${TURBFILE} ]; then
-echo "Found file ${TURBFILE}"
+	cacaomsglog "Found file ${TURBFILE}"
 else
-echo "Creating file ${TURBFILE}"
-sendFPScmd "setval DMatmturb-${CACAO_DMINDEX}.turbseed.comp ON"
-echo "Waiting for file ${TURBFILE}"
-until [ -f ${TURBFILE} ]
-do
-     sleep 0.1
-done
+	cacaomsglog "Creating file ${TURBFILE}"
+	sendFPScmd "setval DMatmturb-${DMINDEX}.turbseed.comp ON"
+	echo "Waiting for file ${TURBFILE}"
+	until [ -f ${TURBFILE} ]
+	do
+		sleep 0.1
+	done
 fi
 
 if [ ${ACTION} == "start" ]; then
-ACTIONOK=1
-sendFPScmd "setval DMatmturb-${CACAO_DMINDEX}.dmstream aol${CACAO_LOOPNUMBER}_dmturb"
-sendFPScmd "confwupdate DMatmturb-${CACAO_DMINDEX}"
-sendFPScmd "runstart DMatmturb-${CACAO_DMINDEX}"
-sendFPScmd "setval DMatmturb-${CACAO_DMINDEX}.turbON ON"
+	ACTIONOK=1
+	cacaomsglog "START"
+	sendFPScmd "setval DMatmturb-${DMINDEX}.dmstream aol${CACAO_LOOPNUMBER}_dmturb"
+	sendFPScmd "confwupdate DMatmturb-${DMINDEX}"
+	sendFPScmd "runstart DMatmturb-${DMINDEX}"
+	sendFPScmd "setval DMatmturb-${DMINDEX}.turbON ON"
 fi
 
 
 if [ ${ACTION} == "stop" ]; then
-ACTIONOK=1
-sendFPScmd "setval DMatmturb-${CACAO_DMINDEX}.turbON OFF"
-sendFPScmd "setval DMatmturb-${CACAO_DMINDEX}.turbZERO ON"
-sendFPScmd "runstop DMatmturb-${CACAO_DMINDEX}"
+	ACTIONOK=1
+	cacaomsglog "STOP"
+	sendFPScmd "setval DMatmturb-${DMINDEX}.turbON OFF"
+	sendFPScmd "setval DMatmturb-${DMINDEX}.turbZERO ON"
+	sendFPScmd "runstop DMatmturb-${DMINDEX}"
 fi
 
 if [ ${ACTION} == "on" ]; then
-ACTIONOK=1
-sendFPScmd "setval DMatmturb-${CACAO_DMINDEX}.turbON ON"
+	ACTIONOK=1
+	cacaomsglog "ON"
+	sendFPScmd "setval DMatmturb-${DMINDEX}.turbON ON"
 fi
 
 if [ ${ACTION} == "off" ]; then
-ACTIONOK=1
-sendFPScmd "setval DMatmturb-${CACAO_DMINDEX}.turbON OFF"
-sendFPScmd "setval DMatmturb-${CACAO_DMINDEX}.turbZERO ON"
+	ACTIONOK=1
+	cacaomsglog "OFF"
+	sendFPScmd "setval DMatmturb-${DMINDEX}.turbON OFF"
+	sendFPScmd "setval DMatmturb-${DMINDEX}.turbZERO ON"
 fi
 
 
 
 if [ ${ACTIONOK} == 0 ]; then
-echo "[$(tput setaf 1)$(tput bold) FAILED $(tput sgr0)] ACTION $ACTION undefined"
+	echo "[$(tput setaf 1)$(tput bold) FAILED $(tput sgr0)] ACTION $ACTION undefined"
+	cacaomsglog "ERROR ACTION undefined"
+	exit 1
 fi
diff --git a/AOloopControl/scripts/aorun/cacao-aorun-120-mstat b/AOloopControl/scripts/aorun/cacao-aorun-120-mstat
--- a/AOloopControl/scripts/aorun/cacao-aorun-120-mstat
+++ b/AOloopControl/scripts/aorun/cacao-aorun-120-mstat
@@ -22,7 +22,7 @@ ACTION="${inputMSargARRAY[0]}"
 ACTIONOK=0
 
 if [ ${ACTION} == "check" ]; then
-ACTIONOK=1
+	ACTIONOK=1
 fi
 
 # Checking FPS
@@ -31,31 +31,36 @@ checkFPSON CACAO_FPSPROC_MODALFILTERING ${CACAO_FPSPROC_MODALFILTERING}
 checkFPSON CACAO_FPSPROC_MODALCTRL_STATS ${CACAO_FPSPROC_MODALCTRL_STATS}
 
 if [ ${FPScheckOK} == "FAIL" ]; then
-echo "[$(tput setaf 1)$(tput bold) FAILED $(tput sgr0)] FPS check failed"
-exit
+	echo "[$(tput setaf 1)$(tput bold) FAILED $(tput sgr0)] FPS check failed"
+	cacaomsglog "ERROR FPScheck"
+	exit 1
 fi
 
 
 
 
 if [ ${ACTION} == "start" ]; then
-ACTIONOK=1
-
-sendFPScmd "setval mctrlstats-${CACAO_LOOPNUMBER}.AOloopindex ${CACAO_LOOPNUMBER}"
-sendFPScmd "confwupdate mctrlstats-${CACAO_LOOPNUMBER}"
-sendFPScmd "runstart mctrlstats-${CACAO_LOOPNUMBER}"
-
+	ACTIONOK=1
+	cacaomsglog "START"
+	sendFPScmd "setval mctrlstats-${CACAO_LOOPNUMBER}.AOloopindex ${CACAO_LOOPNUMBER}"
+	sendFPScmd "confwupdate mctrlstats-${CACAO_LOOPNUMBER}"
+	sendFPScmd "runstart mctrlstats-${CACAO_LOOPNUMBER}"
 fi
 
 
 if [ ${ACTION} == "stop" ]; then
-ACTIONOK=1
-sendFPScmd "runstop mctrlstats-${CACAO_LOOPNUMBER}"
+	ACTIONOK=1
+	cacaomsglog "STOP"
+	sendFPScmd "runstop mctrlstats-${CACAO_LOOPNUMBER}"
 fi
 
 
 
 
 if [ ${ACTIONOK} == 0 ]; then
-echo "[$(tput setaf 1)$(tput bold) FAILED $(tput sgr0)] ACTION $ACTION undefined"
+	echo "[$(tput setaf 1)$(tput bold) FAILED $(tput sgr0)] ACTION $ACTION undefined"
+	cacaomsglog "ERROR ACTION undefined"
+	exit 1
 fi
+
+cacaomsglog "END"
diff --git a/AOloopControl/scripts/aorun/cacao-aorun-130-mkPF b/AOloopControl/scripts/aorun/cacao-aorun-130-mkPF
--- a/AOloopControl/scripts/aorun/cacao-aorun-130-mkPF
+++ b/AOloopControl/scripts/aorun/cacao-aorun-130-mkPF
@@ -17,6 +17,8 @@ source cacao-check-cacaovars
 
 MSarg+=( "block:integer:mode block index" )
 MSarg+=( "action:string:action (start/stop/check)" )
+
+
 source milk-argparse
 
 MBLOCK="${inputMSargARRAY[0]}"
@@ -31,7 +33,7 @@ fpsname="mkPF${BLKindex}"
 ACTIONOK=0
 
 if [ ${ACTION} == "check" ]; then
-ACTIONOK=1
+	ACTIONOK=1
 fi
 
 # Checking FPS
@@ -40,30 +42,37 @@ checkFPSON CACAO_FPSPROC_MODALFILTERING ${CACAO_FPSPROC_MODALFILTERING}
 checkFPSON CACAO_FPSPROC_MKPF ${CACAO_FPSPROC_MKPF}
 
 if [ ${FPScheckOK} == "FAIL" ]; then
-echo "[$(tput setaf 1)$(tput bold) FAILED $(tput sgr0)] FPS check failed"
-exit
+	echo "[$(tput setaf 1)$(tput bold) FAILED $(tput sgr0)] FPS check failed"
+	cacaomsglog "ERROR FPScheck"
+	exit 1
 fi
 
 
 
 
 if [ ${ACTION} == "start" ]; then
-ACTIONOK=1
-sendFPScmd "setval ${fpsname}-${CACAO_LOOPNUMBER}.PFlatency ${CACAO_LATENCYFR}"
-sendFPScmd "confwupdate ${fpsname}-${CACAO_LOOPNUMBER}"
-sendFPScmd "runstart ${fpsname}-${CACAO_LOOPNUMBER}"
-
+	ACTIONOK=1
+	cacaomsglog "START"
+	sendFPScmd "setval ${fpsname}-${CACAO_LOOPNUMBER}.PFlatency ${CACAO_LATENCYFR}"
+	sendFPScmd "confwupdate ${fpsname}-${CACAO_LOOPNUMBER}"
+	sendFPScmd "runstart ${fpsname}-${CACAO_LOOPNUMBER}"
 fi
 
 
 if [ ${ACTION} == "stop" ]; then
-ACTIONOK=1
-sendFPScmd "runstop ${fpsname}-${CACAO_LOOPNUMBER}"
+	ACTIONOK=1
+	cacaomsglog "STOP"
+	sendFPScmd "runstop ${fpsname}-${CACAO_LOOPNUMBER}"
 fi
 
 
 
 
 if [ ${ACTIONOK} == 0 ]; then
-echo "[$(tput setaf 1)$(tput bold) FAILED $(tput sgr0)] ACTION $ACTION undefined"
+	echo "[$(tput setaf 1)$(tput bold) FAILED $(tput sgr0)] ACTION $ACTION undefined"
+	cacaomsglog "ERROR ACTION undefined"
+	exit 1
 fi
+
+
+cacaomsglog "END"
diff --git a/AOloopControl_DM/scripts/cacao-DMastrogrid b/AOloopControl_DM/scripts/cacao-DMastrogrid
--- a/AOloopControl_DM/scripts/cacao-DMastrogrid
+++ b/AOloopControl_DM/scripts/cacao-DMastrogrid
@@ -1,22 +1,20 @@
 #!/usr/bin/env bash
 
 # This script uses milk-argparse
-# See template milk-scriptexample in module milk_module_example for template and instructions
+# See template milk-scriptexample
 
+ASTROGRIDCHANNEL="09"
 
-# script 1-line description
 MSdescr="Run DM astrogrid"
-# Extended description
 MSextdescr="DM grid pattern modulation for astrometry and photometric calibration"
 
 
 source milk-script-std-config
-
 source cacao-check-cacaovars
 
 
-RequiredCommands+=( cacao-astrogrid-mkgrid )
-
+RequiredCommands+=( cacao-astrogrid-mkgrid milk-shmim-zero )
+RequiredFiles=(DMINDEX)
 
 MSarg+=( "action:string:action (start/stop/check)" )
 
@@ -27,17 +25,22 @@ function set_amplitude() {
 	amplitude=$1
 }
 
+
 MSopt+=( "n:nbframe:set_nbframe:nbfr[int]:switch pattern every n AO frames (default=2)" )
 nbframe=2
 function set_nbframe() {
 	nbframe=$1
 }
 
+
+
 MSopt+=( "b:binfact:set_binfact:binfact[int]:bin factor (default=2)" )
 binfact=2
 function set_binfact() {
 	binfact=$1
 }
+
+
 
 MSopt+=( "p:pattern:set_pattern:pattern[int]:pattern (default=0)" )
 pattern=0
@@ -49,17 +52,26 @@ function set_pattern() {
 
 source milk-argparse
 
-
-
-
 ACTION="${inputMSargARRAY[0]}"
 
 
-echo "CACAO_DMINDEX = ${CACAO_DMINDEX}"
+
+if [ -f DMINDEX ]; then
+    DMINDEX=$( head -1 DMINDEX )
+else
+	cacaomsglog "Error: no DMINDEX file. Are we running this from the correct directory ?"
+    exit 1
+fi
+
+echo "DMINDEX = ${DMINDEX}"
 echo "CACAO_LOOPNAME = ${CACAO_LOOPNAME}"
 echo "fpsCTRLfifo = ${fpsCTRLfifo}"
 
 
+cacaomsglog "amplitude ${amplitude}"
+cacaomsglog "nbframe ${nbframe}"
+cacaomsglog "binfact ${binfact}"
+cacaomsglog "pattern ${pattern}"
 
 
 
@@ -67,31 +79,29 @@ echo "$amplitude $nbframe $binfact"
 
 ACTIONOK=0
 
+
+
+
 if [ ${ACTION} = "start" ]; then
-
-echo "start"
-# create XY astrogrid pattern
-cacao-astrogrid-mkgrid -b${binfact} ${pattern}
-
-sendFPScmd "setval DMch2disp-${CACAO_DMINDEX}.astrogrid.nbframe ${nbframe}"
-sendFPScmd "setval DMch2disp-${CACAO_DMINDEX}.astrogrid.delay 0"
-sendFPScmd "setval DMch2disp-${CACAO_DMINDEX}.astrogrid.mult ${amplitude}"
-sendFPScmd "setval DMch2disp-${CACAO_DMINDEX}.astrogrid.mode ON"
-
-ACTIONOK=1
-
+	cacaomsglog "START"
+	# create XY astrogrid pattern
+	cacao-astrogrid-mkgrid -b${binfact} ${pattern}
+	sendFPScmd "setval DMch2disp-${DMINDEX}.astrogrid.chan ${ASTROGRIDCHANNEL}"
+	sendFPScmd "setval DMch2disp-${DMINDEX}.astrogrid.sname aol${CACAO_LOOPNUMBER}_DMastrogrid"
+	sendFPScmd "setval DMch2disp-${DMINDEX}.astrogrid.nbframe ${nbframe}"
+	sendFPScmd "setval DMch2disp-${DMINDEX}.astrogrid.delay 0"
+	sendFPScmd "setval DMch2disp-${DMINDEX}.astrogrid.mult ${amplitude}"
+	sendFPScmd "setval DMch2disp-${DMINDEX}.astrogrid.mode ON"
+	ACTIONOK=1
 fi
 
 
 
 if [ ${ACTION} = "stop" ]; then
-
-echo "stop"
-
-sendFPScmd "setval DMch2disp-${CACAO_DMINDEX}.astrogrid.mode OFF"
-
-ACTIONOK=1
-
+	cacaomsglog "STOP"
+	sendFPScmd "setval DMch2disp-${DMINDEX}.astrogrid.mode OFF"
+	milk-shmim-zero dm${DMINDEX}disp${ASTROGRIDCHANNEL}
+	ACTIONOK=1
 fi
 
 
@@ -103,6 +113,10 @@ fi
 
 
 if [ ${ACTIONOK} == 0 ]; then
-echo "[$(tput setaf 1)$(tput bold) FAILED $(tput sgr0)] ACTION $ACTION undefined"
+	echo "[$(tput setaf 1)$(tput bold) FAILED $(tput sgr0)] ACTION $ACTION undefined"
+	cacaomsglog "ERROR ACTION undefined"
+	exit 1
 fi
 
+
+cacaomsglog "END"
