deploying pre-commit + lint

diff --git a/AOloopControl/scripts/aohardsim/aosimPyrWFS b/AOloopControl/scripts/aohardsim/aosimPyrWFS
--- a/AOloopControl/scripts/aohardsim/aosimPyrWFS
+++ b/AOloopControl/scripts/aohardsim/aosimPyrWFS
@@ -10,29 +10,29 @@ pname=`echo "$0" | sed "s/\.\///g"`
 CONFFILE="$pname.conf" #default
 
 function printHELP {
-echo "------------------------------------------------------------------------"
-echo "$(tput bold) $pname : WFS SIMULATION$(tput sgr 0)"
-echo "------------------------------------------------------------------------"
-echo "  Simulate WFS (currently only Pyramid)"
-echo "   "
-echo " $(tput bold)USAGE:$(tput sgr 0)"
-echo "     $0 [-hc]"
-echo ""
-echo " $(tput bold)OPTIONS:$(tput sgr 0)"
-echo "    $(tput bold)-h$(tput sgr 0)               print help"
-echo "    $(tput bold)-c$(tput sgr 0) <conffile>    use configuration file <conffile>"
-echo "    $(tput bold)-n$(tput sgr 0)               create new template default configuration ($CONFFILE.default) and exit"
-echo ""
-echo " $(tput bold)INPUT:$(tput sgr 0)"
-echo "     aosimPyrWFS.conf     configuration file"
-echo ""
-echo "------------------------------------------------------------------------"
+    echo "------------------------------------------------------------------------"
+    echo "$(tput bold) $pname : WFS SIMULATION$(tput sgr 0)"
+    echo "------------------------------------------------------------------------"
+    echo "  Simulate WFS (currently only Pyramid)"
+    echo "   "
+    echo " $(tput bold)USAGE:$(tput sgr 0)"
+    echo "     $0 [-hc]"
+    echo ""
+    echo " $(tput bold)OPTIONS:$(tput sgr 0)"
+    echo "    $(tput bold)-h$(tput sgr 0)               print help"
+    echo "    $(tput bold)-c$(tput sgr 0) <conffile>    use configuration file <conffile>"
+    echo "    $(tput bold)-n$(tput sgr 0)               create new template default configuration ($CONFFILE.default) and exit"
+    echo ""
+    echo " $(tput bold)INPUT:$(tput sgr 0)"
+    echo "     aosimPyrWFS.conf     configuration file"
+    echo ""
+    echo "------------------------------------------------------------------------"
 }
 
 
 
 function CreateDefaultConfiguration {
-$execname << EOF
+    $execname << EOF
 AOsimPyrWFS "$CONFFILE"
 exit
 EOF
@@ -50,27 +50,27 @@ EOF
 #getopts. This is required to get unrecognized option code to work.
 
 while getopts :hc:n FLAG; do
-  case $FLAG in
-    h)  #show help
-      printHELP
-      exit
-      ;;
-     c) # set configuration file name
-    CONFFILE=$OPTARG
-    ;;
-    n) # create default configuration
-    CreateDefaultConfiguration
-    exit
-    ;;
-   \?) #unrecognized option - show help
-      echo -e \\n"Option -${BOLD}$OPTARG${NORM} not allowed."
-      printHELP
-      #If you just want to display a simple error message instead of the full
-      #help, remove the 2 lines above and uncomment the 2 lines below.
-      #echo -e "Use ${BOLD}$SCRIPT -h${NORM} to see the help documentation."\\n
-      #exit 2
-      ;;
-  esac
+    case $FLAG in
+        h)  #show help
+            printHELP
+            exit
+            ;;
+        c) # set configuration file name
+            CONFFILE=$OPTARG
+            ;;
+        n) # create default configuration
+            CreateDefaultConfiguration
+            exit
+            ;;
+        \?) #unrecognized option - show help
+            echo -e \\n"Option -${BOLD}$OPTARG${NORM} not allowed."
+            printHELP
+            #If you just want to display a simple error message instead of the full
+            #help, remove the 2 lines above and uncomment the 2 lines below.
+            #echo -e "Use ${BOLD}$SCRIPT -h${NORM} to see the help documentation."\\n
+            #exit 2
+            ;;
+    esac
 done
 
 shift $((OPTIND-1))  #This tells getopts to move on to the next argument.
@@ -81,24 +81,24 @@ shift $((OPTIND-1))  #This tells getopts to move on to the next argument.
 
 
 if [ "$1" = "help" ] || [ "$#" -ne $NBARGS ]; then
-if [ "$#" -ne $NBARGS ]; then
-    echo "$(tput setaf 1)$(tput bold) Illegal number of parameters ($NBARGS params required, $# entered) $(tput sgr 0)"
-fi
-printHELP
-        exit
+    if [ "$#" -ne $NBARGS ]; then
+        echo "$(tput setaf 1)$(tput bold) Illegal number of parameters ($NBARGS params required, $# entered) $(tput sgr 0)"
+    fi
+    printHELP
+    exit
 fi
 
 
 if [ ! -f $CONFFILE ]
-  then
+then
     echo "$(tput setaf 5)$(tput bold) WARNING: File $CONFFILE not found $(tput sgr 0)"
     echo "$(tput setaf 5)$(tput bold) WARNING: Copying $pname.conf.default to $CONFFILE  $(tput sgr 0)"
     if [ -f "$pname.conf.default" ]; then
-    cp $pname.conf.default $CONFFILE
+        cp $pname.conf.default $CONFFILE
     else
-    echo "$(tput setaf 5)$(tput bold) WARNING: File $pname.conf.default not found $(tput sgr 0) -> creating it"
-    CreateDefaultConfiguration
-    cp $pname.conf.default $CONFFILE
+        echo "$(tput setaf 5)$(tput bold) WARNING: File $pname.conf.default not found $(tput sgr 0) -> creating it"
+        CreateDefaultConfiguration
+        cp $pname.conf.default $CONFFILE
     fi
 fi
 
diff --git a/AOloopControl/scripts/aohardsim/aosimcoroLOWFS b/AOloopControl/scripts/aohardsim/aosimcoroLOWFS
--- a/AOloopControl/scripts/aohardsim/aosimcoroLOWFS
+++ b/AOloopControl/scripts/aohardsim/aosimcoroLOWFS
@@ -21,29 +21,29 @@ LOWFSOPDMAP="$CONFDIR/aosimlowfsopdmap.fits"
 mkdir -p $CONFDIR
 
 function printHELP {
-echo "------------------------------------------------------------------------"
-echo "$(tput bold) $pname : CORONAGRAPH + LOWFS SIMULATION (tput sgr 0)"
-echo "------------------------------------------------------------------------"
-echo "  Simulate simple coronagraph + LOWFS"
-echo "   "
-echo " $(tput bold)USAGE:$(tput sgr 0)"
-echo "     $0 [-hcin]"
-echo ""
-echo " $(tput bold)OPTIONS:$(tput sgr 0)"
-echo "    $(tput bold)-h$(tput sgr 0)               print (h)elp"
-echo "    $(tput bold)-c$(tput sgr 0) <conffile>    adopt (c)onfiguration file <conffile>"
-echo "    $(tput bold)-i$(tput sgr 0) <arraysize>   (i)nit masks"
-echo "    $(tput bold)-n$(tput sgr 0)               create new template default configuration -> $CONFFILE"
-echo ""
-echo " $(tput bold)REQUIRED:$(tput sgr 0)"
-echo "     $CONFFILE     configuration file"
-echo "     $COROFPMAMP    coronagraph focal plane mask amplitude"
-echo "     $COROFPMPHA    coronagraph focal plane mask phase"
-echo "     $LYOTSTOPRAMP  coronagraph Lyot stop reflected light amplitude"
-echo "     $ LYOTSTOPRPHA coronagraph Lyot stop reflected light phase"
-echo "     $LYOTSTOPTPHA  coronagraph Lyot stop transmitted light amplitude"
-echo "     $LOWFSOPDMAP  coronagraph Lyot stop transmitted light phase"
-echo "------------------------------------------------------------------------"
+    echo "------------------------------------------------------------------------"
+    echo "$(tput bold) $pname : CORONAGRAPH + LOWFS SIMULATION (tput sgr 0)"
+    echo "------------------------------------------------------------------------"
+    echo "  Simulate simple coronagraph + LOWFS"
+    echo "   "
+    echo " $(tput bold)USAGE:$(tput sgr 0)"
+    echo "     $0 [-hcin]"
+    echo ""
+    echo " $(tput bold)OPTIONS:$(tput sgr 0)"
+    echo "    $(tput bold)-h$(tput sgr 0)               print (h)elp"
+    echo "    $(tput bold)-c$(tput sgr 0) <conffile>    adopt (c)onfiguration file <conffile>"
+    echo "    $(tput bold)-i$(tput sgr 0) <arraysize>   (i)nit masks"
+    echo "    $(tput bold)-n$(tput sgr 0)               create new template default configuration -> $CONFFILE"
+    echo ""
+    echo " $(tput bold)REQUIRED:$(tput sgr 0)"
+    echo "     $CONFFILE     configuration file"
+    echo "     $COROFPMAMP    coronagraph focal plane mask amplitude"
+    echo "     $COROFPMPHA    coronagraph focal plane mask phase"
+    echo "     $LYOTSTOPRAMP  coronagraph Lyot stop reflected light amplitude"
+    echo "     $ LYOTSTOPRPHA coronagraph Lyot stop reflected light phase"
+    echo "     $LYOTSTOPTPHA  coronagraph Lyot stop transmitted light amplitude"
+    echo "     $LOWFSOPDMAP  coronagraph Lyot stop transmitted light phase"
+    echo "------------------------------------------------------------------------"
 }
 
 
@@ -52,21 +52,21 @@ EXITSTATUS=0
 
 
 function checkFile {
-if [ -f $1 ]
-  then
-    echo "[$(tput setaf 2)$(tput bold)   OK   $(tput sgr 0)] File $1 found"
-   else
-    echo "[$(tput setaf 1)$(tput bold) FAILED $(tput sgr 0)] File $1 not found"
-    EXITSTATUS=1
-fi
+    if [ -f $1 ]
+    then
+        echo "[$(tput setaf 2)$(tput bold)   OK   $(tput sgr 0)] File $1 found"
+    else
+        echo "[$(tput setaf 1)$(tput bold) FAILED $(tput sgr 0)] File $1 not found"
+        EXITSTATUS=1
+    fi
 }
 
 
 
 function initMasks {
-mkdir -p conf
+    mkdir -p conf
 
-$execname << EOF
+    $execname << EOF
 cx=0.5*$1
 cy=0.5*$1
 mkdisk fa $1 $1 cx cy cx
@@ -98,7 +98,7 @@ EOF
 
 
 function CreateDefaultConfiguration {
-$execname << EOF
+    $execname << EOF
 AOsimcoroLOWFS "$CONFFILE"
 exit
 EOF
@@ -114,30 +114,30 @@ EOF
 #getopts. This is required to get unrecognized option code to work.
 
 while getopts :hc:i:n FLAG; do
-  case $FLAG in
-    h)  #show help
-      printHELP
-      exit
-      ;;
-     c) # set configuration file name
-    CONFFILE=$OPTARG
-    ;;
-    i) # init required masks to simple configuration, arg = arraysize
-    initMasks $OPTARG
-    ;;
-    n) # create default configuration
-    CreateDefaultConfiguration
-    exit
-    ;;
-   \?) #unrecognized option - show help
-      echo -e \\n"Option -${BOLD}$OPTARG${NORM} not allowed."
-      printHELP
-      #If you just want to display a simple error message instead of the full
-      #help, remove the 2 lines above and uncomment the 2 lines below.
-      #echo -e "Use ${BOLD}$SCRIPT -h${NORM} to see the help documentation."\\n
-      #exit 2
-      ;;
-  esac
+    case $FLAG in
+        h)  #show help
+            printHELP
+            exit
+            ;;
+        c) # set configuration file name
+            CONFFILE=$OPTARG
+            ;;
+        i) # init required masks to simple configuration, arg = arraysize
+            initMasks $OPTARG
+            ;;
+        n) # create default configuration
+            CreateDefaultConfiguration
+            exit
+            ;;
+        \?) #unrecognized option - show help
+            echo -e \\n"Option -${BOLD}$OPTARG${NORM} not allowed."
+            printHELP
+            #If you just want to display a simple error message instead of the full
+            #help, remove the 2 lines above and uncomment the 2 lines below.
+            #echo -e "Use ${BOLD}$SCRIPT -h${NORM} to see the help documentation."\\n
+            #exit 2
+            ;;
+    esac
 done
 
 shift $((OPTIND-1))  #This tells getopts to move on to the next argument.
@@ -148,11 +148,11 @@ shift $((OPTIND-1))  #This tells getopts to move on to the next argument.
 
 
 if [ "$1" = "help" ] || [ "$#" -ne $NBARGS ]; then
-if [ "$#" -ne $NBARGS ]; then
-    echo "$(tput setaf 1)$(tput bold) Illegal number of parameters ($NBARGS params required, $# entered) $(tput sgr 0)"
-fi
-printHELP
-        exit
+    if [ "$#" -ne $NBARGS ]; then
+        echo "$(tput setaf 1)$(tput bold) Illegal number of parameters ($NBARGS params required, $# entered) $(tput sgr 0)"
+    fi
+    printHELP
+    exit
 fi
 
 
@@ -173,25 +173,25 @@ checkFile $LOWFSOPDMAP
 
 
 if [ $EXITSTATUS -eq 1 ]; then
-echo ""
-echo "$(tput setaf 1)$(tput bold) REQUIRED FILES NOT FOUND: CREATING THEM $(tput sgr 0)"
-initMasks 256
-EXITSTATUS=0
+    echo ""
+    echo "$(tput setaf 1)$(tput bold) REQUIRED FILES NOT FOUND: CREATING THEM $(tput sgr 0)"
+    initMasks 256
+    EXITSTATUS=0
 fi
 
 
 
 
 if [ ! -f $CONFFILE ]
-  then
+then
     echo "$(tput setaf 5)$(tput bold) WARNING: File $CONFFILE not found $(tput sgr 0)"
     echo "$(tput setaf 5)$(tput bold) WARNING: Copying $pname.conf.default to $CONFFILE  $(tput sgr 0)"
     if [ -f "$pname.conf.default" ]; then
-    cp $pname.conf.default $CONFFILE
+        cp $pname.conf.default $CONFFILE
     else
-    echo "$(tput setaf 5)$(tput bold) WARNING: File $pname.conf.default not found $(tput sgr 0) -> creating it"
-    CreateDefaultConfiguration
-    cp $pname.conf.default $CONFFILE
+        echo "$(tput setaf 5)$(tput bold) WARNING: File $pname.conf.default not found $(tput sgr 0) -> creating it"
+        CreateDefaultConfiguration
+        cp $pname.conf.default $CONFFILE
     fi
 fi
 
diff --git a/AOloopControl/scripts/cacao-RMdecode b/AOloopControl/scripts/cacao-RMdecode
--- a/AOloopControl/scripts/cacao-RMdecode
+++ b/AOloopControl/scripts/cacao-RMdecode
@@ -10,39 +10,39 @@ pname=`echo "$0" | sed "s/\.\///g"`
 
 
 function printHELP {
-echo "------------------------------------------------------------------------"
-echo "$(tput bold) $pname : Decode zonal resp matrix $(tput sgr0)"
-echo "------------------------------------------------------------------------"
-echo "Cleans zonal response matrices in ./tmpRMacqu/ directory"
-echo "if images conf/RMpixindex.fits conf/RMmat.fits exist, use them for coding/decoding"
-echo "   "
-echo " $(tput bold)USAGE:$(tput sgr0)"
-echo "     $0 [-h] <FPSname>"
-echo ""
-echo " $(tput bold)OPTIONS:$(tput sgr0)"
-echo "     $(tput bold)-h$(tput sgr0)          help"
-echo ""
-echo " $(tput bold)INPUT:$(tput sgr0)"
-echo "     <FPSname>      Function Parameter Structure (FPS) name"
-echo ""
-echo " $(tput bold)OUTPUT:$(tput sgr0)"
-echo "  zrespmat.fits    : zonal response matrix"
-echo "  wfsref0.fits     : wfs reference"
-echo "  wfsmap.fits      : WFS response map"
-echo "  dmmap.fits       : DM response map"
-echo "     wfsmask.fits"
-echo "     dmmaskRM.fits"
-echo "     dmslaved.fits"
-echo "     dmmask.fits" 
-echo ""
-echo "------------------------------------------------------------------------"
+    echo "------------------------------------------------------------------------"
+    echo "$(tput bold) $pname : Decode zonal resp matrix $(tput sgr0)"
+    echo "------------------------------------------------------------------------"
+    echo "Cleans zonal response matrices in ./tmpRMacqu/ directory"
+    echo "if images conf/RMpixindex.fits conf/RMmat.fits exist, use them for coding/decoding"
+    echo "   "
+    echo " $(tput bold)USAGE:$(tput sgr0)"
+    echo "     $0 [-h] <FPSname>"
+    echo ""
+    echo " $(tput bold)OPTIONS:$(tput sgr0)"
+    echo "     $(tput bold)-h$(tput sgr0)          help"
+    echo ""
+    echo " $(tput bold)INPUT:$(tput sgr0)"
+    echo "     <FPSname>      Function Parameter Structure (FPS) name"
+    echo ""
+    echo " $(tput bold)OUTPUT:$(tput sgr0)"
+    echo "  zrespmat.fits    : zonal response matrix"
+    echo "  wfsref0.fits     : wfs reference"
+    echo "  wfsmap.fits      : WFS response map"
+    echo "  dmmap.fits       : DM response map"
+    echo "     wfsmask.fits"
+    echo "     dmmaskRM.fits"
+    echo "     dmslaved.fits"
+    echo "     dmmask.fits"
+    echo ""
+    echo "------------------------------------------------------------------------"
 }
 
 
 
 printHELP1 ()
 {
-    printf "     $(tput bold)%-25s$(tput sgr0)       Cleans zonal resp matrix\n" "$0" 
+    printf "     $(tput bold)%-25s$(tput sgr0)       Cleans zonal resp matrix\n" "$0"
 }
 
 
@@ -52,21 +52,21 @@ EXITSTATUS=0
 
 
 function checkFile {
-	if [ -f $1 ]; then
-		echo "[$(tput setaf 2)$(tput bold)   OK   $(tput sgr0)] File $(tput bold)$1$(tput sgr0) found"
-	else
-		echo "[$(tput setaf 1)$(tput bold) FAILED $(tput sgr0)] File $(tput bold)$1$(tput sgr0) not found"
-		EXITSTATUS=1
-	fi
+    if [ -f $1 ]; then
+        echo "[$(tput setaf 2)$(tput bold)   OK   $(tput sgr0)] File $(tput bold)$1$(tput sgr0) found"
+    else
+        echo "[$(tput setaf 1)$(tput bold) FAILED $(tput sgr0)] File $(tput bold)$1$(tput sgr0) not found"
+        EXITSTATUS=1
+    fi
 }
 
 function checkDir {
-	if [ -d $1 ]; then
-		echo "[$(tput setaf 2)$(tput bold)   OK   $(tput sgr0)] Directory $(tput bold)$1$(tput sgr0) found"
-	else
-		echo "[$(tput setaf 1)$(tput bold) FAILED $(tput sgr0)] Directory $(tput bold)$1$(tput sgr0) not found"
-		EXITSTATUS=1
-	fi
+    if [ -d $1 ]; then
+        echo "[$(tput setaf 2)$(tput bold)   OK   $(tput sgr0)] Directory $(tput bold)$1$(tput sgr0) found"
+    else
+        echo "[$(tput setaf 1)$(tput bold) FAILED $(tput sgr0)] Directory $(tput bold)$1$(tput sgr0) not found"
+        EXITSTATUS=1
+    fi
 }
 
 
@@ -75,15 +75,15 @@ function checkDir {
 # Transform long options to short ones
 singlelinehelp=0
 for arg in "$@"; do
-  shift
-  case "$arg" in
-    "--help") set -- "$@" "-h" ;;
-    "--help1") 
-set -- "$@" "-h" 
-singlelinehelp=1;
-;;
-    *)        set -- "$@" "$arg"
-  esac
+    shift
+    case "$arg" in
+        "--help") set -- "$@" "-h" ;;
+        "--help1")
+            set -- "$@" "-h"
+            singlelinehelp=1;
+            ;;
+        *)        set -- "$@" "$arg"
+    esac
 done
 
 
@@ -91,23 +91,23 @@ done
 
 
 while getopts :h FLAG; do
-  case $FLAG in
-    h)  #show help
-      if [ "$singlelinehelp" -eq "0" ]; then
-      printHELP
-      else
-      printHELP1
-      fi
-      exit
-      ;;
-    \?) #unrecognized option - show help
-      echo -e \\n"Option -${BOLD}$OPTARG${NORM} not allowed."
-      printHELP
-      ;;
-  esac
+    case $FLAG in
+        h)  #show help
+            if [ "$singlelinehelp" -eq "0" ]; then
+                printHELP
+            else
+                printHELP1
+            fi
+            exit
+            ;;
+        \?) #unrecognized option - show help
+            echo -e \\n"Option -${BOLD}$OPTARG${NORM} not allowed."
+            printHELP
+            ;;
+    esac
 done
 
-shift $((OPTIND-1)) 
+shift $((OPTIND-1))
 
 
 
@@ -115,11 +115,11 @@ shift $((OPTIND-1))
 
 
 if [ "$1" = "help" ] || [ "$#" -ne $NBARGS ]; then
-if [ "$#" -ne $NBARGS ]; then
-    echo "$(tput setaf 1)$(tput bold) Illegal number of parameters ($NBARGS params required, $# entered) $(tput sgr0)"
-fi
-printHELP
-        exit
+    if [ "$#" -ne $NBARGS ]; then
+        echo "$(tput setaf 1)$(tput bold) Illegal number of parameters ($NBARGS params required, $# entered) $(tput sgr0)"
+    fi
+    printHELP
+    exit
 fi
 
 
@@ -132,10 +132,10 @@ fi
 checkFile $1
 
 if [ ${EXITSTATUS} -eq 1 ]; then
-	echo "$(tput setaf 1)$(tput bold) -> EXITING $(tput sgr0)"
-	exit ${EXITSTATUS}
+    echo "$(tput setaf 1)$(tput bold) -> EXITING $(tput sgr0)"
+    exit ${EXITSTATUS}
 else
-	echo ""
+    echo ""
 fi
 
 
@@ -165,8 +165,8 @@ echo "FPStimestring : ${FPStimestring}"
 checkDir ${datadir}
 
 if [ ${EXITSTATUS} -eq 1 ]; then
-	echo "$(tput setaf 1)$(tput bold) -> EXITING $(tput sgr0)"
-	exit ${EXITSTATUS}
+    echo "$(tput setaf 1)$(tput bold) -> EXITING $(tput sgr0)"
+    exit ${EXITSTATUS}
 fi
 
 
@@ -174,13 +174,13 @@ fi
 
 
 if [ ${HpokeMode} = "ON" ]; then
-  echo "Using Hadamard encoding"
-  fileRMmat="${datadir}/Hmat.fits"
-  fileRMpixindex="${datadir}/Hpixindex.fits"
+    echo "Using Hadamard encoding"
+    fileRMmat="${datadir}/Hmat.fits"
+    fileRMpixindex="${datadir}/Hpixindex.fits"
 else
-  echo "Using straight encoding"
-  fileRMmat="${datadir}/RMmat.fits"
-  fileRMpixindex="${datadir}/RMpixindex.fits"
+    echo "Using straight encoding"
+    fileRMmat="${datadir}/RMmat.fits"
+    fileRMpixindex="${datadir}/RMpixindex.fits"
 fi
 
 
@@ -238,14 +238,14 @@ exit
 
 AVEFILECOUNTER=0
 while [  $AVEFILECOUNTER -lt 100 ]; do
-cntnum=$( echo ${AVEFILECOUNTER} | awk '{printf("%03d", $1)}')
-zrespM_filename="./${stageddir}/respM.ave${cntnum}.fits"
-wfsref_filename="./${stageddir}/wfsref.ave${cntnum}.fits"
+    cntnum=$( echo ${AVEFILECOUNTER} | awk '{printf("%03d", $1)}')
+    zrespM_filename="./${stageddir}/respM.ave${cntnum}.fits"
+    wfsref_filename="./${stageddir}/wfsref.ave${cntnum}.fits"
 
-if [ -f "$zrespM_filename" ]; then
+    if [ -f "$zrespM_filename" ]; then
 
 
-OMP_NUM_THREADS=6 cacao -n $pname << EOF
+        OMP_NUM_THREADS=6 cacao -n $pname << EOF
 cacao.aolnb $loopnb
 loadfits "./${stageddir}/RMpokeCube.fits" RMpokeC
 loadfits "./${stageddir}/RMmat.fits" RMmat
@@ -260,9 +260,7 @@ listim
 exitCLI
 EOF
 
-fi
+    fi
 
-let AVEFILECOUNTER=AVEFILECOUNTER+1 
+    let AVEFILECOUNTER=AVEFILECOUNTER+1
 done
-
-
